const { HttpsError } = require('firebase-functions/v2/https')
const { createHash } = require('node:crypto')
const { tenantActor, hasPermission, id } = require('./authorization.cjs')
const permissions = { openAccount:'orders.manage', addRound:'orders.manage', updateRoundStatus:'orders.manage', cancelRound:'orders.manage', requestBill:'orders.manage', reopenBill:'cash.close', recordPayment:'cash.close', inventoryMovement:'inventory.manage', openShift:'cash.close', closeShift:'cash.close', courtesy:'orders.manage', void:'cash.close' }
const money = value => Math.round((value + Number.EPSILON) * 100) / 100
const amount = value => { const number = Number(value); if (!Number.isFinite(number) || number < 0) throw new HttpsError('invalid-argument','Monto inválido.'); return money(number) }
const text = (value,max=200) => { if (typeof value !== 'string' || !value.trim() || value.trim().length > max) throw new HttpsError('invalid-argument','Texto inválido.'); return value.trim() }
const canonical = value => Array.isArray(value) ? value.map(canonical) : value && typeof value === 'object' ? Object.fromEntries(Object.keys(value).sort().map(key => [key, canonical(value[key])])) : value
const fingerprint = value => createHash('sha256').update(JSON.stringify(canonical(value))).digest('hex')
async function executeNightclubCommand(db, request) {
  const input = request.data || {}, type = input.commandType || input.action, permission = permissions[type]
  if (!permission) throw new HttpsError('invalid-argument','Comando Nightclub no reconocido.')
  const operationId = id(input.operationId), actor = await tenantActor(db, request, permission)
  if (actor.tenant.businessType !== 'nightclub_lounge') throw new HttpsError('failed-precondition','La empresa no usa la plantilla Nightclub.')
  const branchId = id(input.branchId), payload = input.payload || {}, requestHash = fingerprint({ type, branchId, payload })
  const root = actor.root, operationRef = root.collection('nightclubOperations').doc(operationId), now = new Date().toISOString()
  return db.runTransaction(async tx => {
    const [stored, tenant, member] = await Promise.all([tx.get(operationRef), tx.get(root), tx.get(root.collection('members').doc(actor.uid))])
    if (stored.exists) {
      const previous = stored.data()
      if (previous.actorUid !== actor.uid || previous.requestHash !== requestHash) throw new HttpsError('already-exists','operationId ya pertenece a otra solicitud.')
      return previous.result
    }
    if (!hasPermission(tenant.data(), member.data(), permission)) throw new HttpsError('permission-denied','Permiso revocado.')
    if (!member.data().branchIds?.includes(branchId)) throw new HttpsError('permission-denied','Sucursal no autorizada.')
    const result = await applyCommand({ db, tx, root, actor, branchId, operationId, type, payload, now })
    tx.create(operationRef, { operationId, tenantId: actor.tenantId, branchId, actorUid: actor.uid, type, requestHash, status:'confirmed', createdAt: now, result })
    tx.create(root.collection('nightclubAudit').doc(), { operationId, tenantId: actor.tenantId, branchId, actorUid: actor.uid, type, resourceId: result.accountId || result.roundId || result.shiftId || result.movementId || null, createdAt: now })
    return result
  })
}
async function applyCommand(context) {
  const { tx, root, actor, branchId, operationId, type, payload, now } = context
  const stateRef = root.collection('nightclubOperationalState').doc(branchId)
  if (type === 'openShift') {
    const state = await tx.get(stateRef); if (state.data()?.activeShiftId) throw new HttpsError('failed-precondition','Ya existe un turno abierto.')
    const shiftId = `shift_${operationId}`, openingFloat = amount(payload.openingFloat), ref = root.collection('nightclubShifts').doc(shiftId)
    tx.create(ref,{ id:shiftId,tenantId:actor.tenantId,branchId,status:'open',openingFloat,openedAt:now,openedBy:actor.uid }); tx.set(stateRef,{ activeShiftId:shiftId,updatedAt:now },{merge:true}); return { shiftId }
  }
  const state = await tx.get(stateRef), activeShiftId = state.data()?.activeShiftId
  if (!activeShiftId) throw new HttpsError('failed-precondition','No hay turno activo.')
  if (type === 'openAccount') {
    const target = payload.target; if (!target || !['table','customer'].includes(target.type)) throw new HttpsError('invalid-argument','Destino inválido.')
    let tableRef, table
    if (target.type === 'table') { tableRef=root.collection('nightclubTables').doc(id(target.tableId)); table=await tx.get(tableRef); if (!table.exists || table.data().activeAccountId) throw new HttpsError('aborted','La mesa ya no está disponible.') }
    else if (!text(target.displayName,100)) throw new HttpsError('invalid-argument','Cliente requerido.')
    const accountId=`account_${operationId}`, ref=root.collection('nightclubAccounts').doc(accountId), value={ id:accountId,tenantId:actor.tenantId,branchId,shiftId:activeShiftId,serviceTarget:target,status:'open',subtotal:0,paidTotal:0,balance:0,openedAt:now,openedBy:actor.uid }
    tx.create(ref,value); if (tableRef) tx.update(tableRef,{activeAccountId:accountId,status:'occupied',updatedAt:now}); return {accountId}
  }
  if (type === 'addRound') {
    const accountId=id(payload.accountId), accountRef=root.collection('nightclubAccounts').doc(accountId), account=await tx.get(accountRef)
    if (!account.exists || account.data().status !== 'open') throw new HttpsError('aborted','La cuenta ya no acepta rondas.')
    if (!Array.isArray(payload.items) || !payload.items.length) throw new HttpsError('invalid-argument','Ronda vacía.')
    const productRefs=payload.items.map(row=>root.collection('nightclubProducts').doc(id(row.productId))), products=await Promise.all(productRefs.map(ref=>tx.get(ref)))
    const requirements=new Map(), lines=[]
    payload.items.forEach((row,index)=>{ const product=products[index].data(), quantity=Number(row.quantity); if (!product || product.active===false || !Number.isInteger(quantity) || quantity<=0) throw new HttpsError('invalid-argument','Producto inválido.'); for(const part of product.recipe||[]) requirements.set(part.inventoryId,(requirements.get(part.inventoryId)||0)+part.quantity*quantity); lines.push({productId:products[index].id,name:product.name,quantity,unitPrice:product.price,lineTotal:money(product.price*quantity),preparationArea:product.preparationArea}) })
    const inventoryRefs=[...requirements.keys()].map(key=>root.collection('nightclubInventory').doc(key)), stocks=await Promise.all(inventoryRefs.map(ref=>tx.get(ref))), consumption=[]
    inventoryRefs.forEach((ref,index)=>{ const required=requirements.get(ref.id), stock=stocks[index].data(); if(!stock || stock.current<required) throw new HttpsError('aborted',`Stock insuficiente: ${stock?.name||ref.id}.`); const current=money(stock.current-required); tx.update(ref,{current,updatedAt:now}); const movementRef=root.collection('nightclubInventoryMovements').doc(`${operationId}_${ref.id}`); tx.create(movementRef,{id:movementRef.id,operationId,tenantId:actor.tenantId,branchId,inventoryId:ref.id,quantity:-required,previous:stock.current,current,type:'sale',actorUid:actor.uid,createdAt:now}); consumption.push({inventoryId:ref.id,quantity:required}) })
    const roundId=`round_${operationId}`, total=money(lines.reduce((sum,row)=>sum+row.lineTotal,0)), status=lines.some(row=>row.preparationArea==='Barra')?'pending':'ready'
    tx.create(root.collection('nightclubRounds').doc(roundId),{id:roundId,tenantId:actor.tenantId,branchId,shiftId:activeShiftId,accountId,items:lines,consumption,status,createdAt:now,createdBy:actor.uid}); tx.update(accountRef,{subtotal:money(account.data().subtotal+total),balance:money(account.data().balance+total),updatedAt:now}); return {roundId,accountId,total}
  }
  if (type === 'requestBill' || type === 'reopenBill') { const accountId=id(payload.accountId), ref=root.collection('nightclubAccounts').doc(accountId), snap=await tx.get(ref), expected=type==='requestBill'?'open':'bill_requested'; if(!snap.exists||snap.data().status!==expected) throw new HttpsError('aborted','La cuenta cambió de estado.'); const status=type==='requestBill'?'bill_requested':'open'; tx.update(ref,{status,updatedAt:now}); const target=snap.data().serviceTarget; if(target?.type==='table') tx.update(root.collection('nightclubTables').doc(target.tableId),{status:status==='open'?'occupied':'bill_requested',updatedAt:now}); return {accountId,status} }
  if (type === 'updateRoundStatus') { const roundId=id(payload.roundId), ref=root.collection('nightclubRounds').doc(roundId), snap=await tx.get(ref), next={pending:'preparing',preparing:'ready',ready:'delivered'}[snap.data()?.status]; if(!snap.exists||!next) throw new HttpsError('aborted','La ronda cambió de estado.'); tx.update(ref,{status:next,updatedAt:now,updatedBy:actor.uid}); return {roundId,status:next} }
  if (type === 'cancelRound') { const roundId=id(payload.roundId), ref=root.collection('nightclubRounds').doc(roundId), round=await tx.get(ref); if(!round.exists) throw new HttpsError('not-found','Ronda no encontrada.'); if(round.data().status==='cancelled') return {roundId,status:'cancelled'}; text(payload.reason,200); const accountRef=root.collection('nightclubAccounts').doc(round.data().accountId), account=await tx.get(accountRef); if((account.data()?.paidTotal||0)>0) throw new HttpsError('failed-precondition','No se anula después de cobrar.'); const refs=(round.data().consumption||[]).map(row=>root.collection('nightclubInventory').doc(row.inventoryId)), stocks=await Promise.all(refs.map(ref=>tx.get(ref))); refs.forEach((stockRef,index)=>{const consumed=round.data().consumption[index], before=stocks[index].data().current, current=money(before+consumed.quantity); tx.update(stockRef,{current,updatedAt:now}); tx.create(root.collection('nightclubInventoryMovements').doc(`${operationId}_${stockRef.id}`),{operationId,inventoryId:stockRef.id,quantity:consumed.quantity,previous:before,current,type:'reversal',reason:payload.reason,actorUid:actor.uid,createdAt:now,tenantId:actor.tenantId,branchId})}); const total=money(round.data().items.reduce((sum,row)=>sum+row.lineTotal,0)); tx.update(ref,{status:'cancelled',cancelledAt:now,cancelledBy:actor.uid,reason:payload.reason}); tx.update(accountRef,{subtotal:money(account.data().subtotal-total),balance:money(account.data().balance-total),updatedAt:now}); return {roundId,status:'cancelled'} }
  if (type === 'recordPayment') { const accountId=id(payload.accountId), ref=root.collection('nightclubAccounts').doc(accountId), snap=await tx.get(ref); if(!snap.exists||snap.data().status!=='bill_requested') throw new HttpsError('aborted','La cuenta no está por cobrar.'); const balance=amount(snap.data().balance), paid=amount(payload.amount), method=text(payload.method,20); if(paid<=0||paid>balance||!['cash','qr','card','mixed'].includes(method)) throw new HttpsError('invalid-argument','Pago inválido.'); const cashAmount=amount(method==='cash'?paid:method==='mixed'?payload.cashAmount:0), qrAmount=amount(method==='qr'?paid:method==='mixed'?payload.qrAmount:0), cardAmount=amount(method==='card'?paid:method==='mixed'?payload.cardAmount:0); if(money(cashAmount+qrAmount+cardAmount)!==paid) throw new HttpsError('invalid-argument','El desglose del pago no coincide.'); const received=amount(payload.received ?? cashAmount); if(received<cashAmount) throw new HttpsError('invalid-argument','Efectivo recibido insuficiente.'); const remaining=money(balance-paid), paymentId=`payment_${operationId}`; tx.create(root.collection('nightclubPayments').doc(paymentId),{id:paymentId,operationId,tenantId:actor.tenantId,branchId,shiftId:activeShiftId,accountId,method,amount:paid,cashAmount,qrAmount,cardAmount,received,change:money(received-cashAmount),createdAt:now,actorUid:actor.uid}); if(cashAmount>0) { const movementId=`cash_${operationId}`; tx.create(root.collection('nightclubCashMovements').doc(movementId),{id:movementId,operationId,tenantId:actor.tenantId,branchId,shiftId:activeShiftId,accountId,type:'sale',amount:cashAmount,actorUid:actor.uid,createdAt:now}) } tx.update(ref,{paidTotal:money((snap.data().paidTotal||0)+paid),balance:remaining,status:remaining===0?'closed':'bill_requested',updatedAt:now}); if(remaining===0&&snap.data().serviceTarget?.type==='table') tx.update(root.collection('nightclubTables').doc(snap.data().serviceTarget.tableId),{status:'available',activeAccountId:null,updatedAt:now}); return {accountId,paymentId,balance:remaining} }
  if (type === 'inventoryMovement') { const inventoryId=id(payload.inventoryId), ref=root.collection('nightclubInventory').doc(inventoryId), snap=await tx.get(ref), quantity=Number(payload.quantity); if(!snap.exists||!Number.isFinite(quantity)||quantity===0||snap.data().current+quantity<0) throw new HttpsError('invalid-argument','Movimiento inválido.'); const current=money(snap.data().current+quantity), movementId=`movement_${operationId}`; tx.update(ref,{current,updatedAt:now}); tx.create(root.collection('nightclubInventoryMovements').doc(movementId),{id:movementId,operationId,tenantId:actor.tenantId,branchId,inventoryId,quantity,previous:snap.data().current,current,type:text(payload.movementType,30),reason:text(payload.reason,200),actorUid:actor.uid,createdAt:now}); return {movementId,current} }
  if (type === 'closeShift') { const shiftId=id(payload.shiftId); if(shiftId!==activeShiftId) throw new HttpsError('aborted','El turno cambió.'); const open=await tx.get(root.collection('nightclubAccounts').where('shiftId','==',shiftId).where('status','in',['open','bill_requested'])); if(!open.empty) throw new HttpsError('failed-precondition','Existen cuentas con saldo.'); const countedCash=amount(payload.countedCash), shiftRef=root.collection('nightclubShifts').doc(shiftId), shift=await tx.get(shiftRef); tx.update(shiftRef,{status:'closed',countedCash,closedAt:now,closedBy:actor.uid}); tx.set(stateRef,{activeShiftId:null,updatedAt:now},{merge:true}); return {shiftId,countedCash,openingFloat:shift.data().openingFloat} }
  throw new HttpsError('failed-precondition','Cortesías y anulaciones requieren una política de autorización antes de habilitarse.')
}
module.exports = { executeNightclubCommand }
