/* eslint-disable @typescript-eslint/ban-ts-comment */
// @ts-nocheck
import assert from 'node:assert/strict'
import test from 'node:test'
import { createNightclubOperation, MemoryNightclubOutboxStore, NightclubSyncEngine } from '../nightclubOutbox.ts'
import { NightclubCommandClient, createNightclubGatewayTransport } from '../nightclubCommandClient.ts'
const operation = (id = 'op-1') => createNightclubOperation({ operationId: id, tenantId: 'tenant-a', branchId: 'main', actorUid: 'waiter-a', type: 'addRound', payload: { accountId: 'account-1' } }, '2026-09-25T20:00:00Z')
test('durable write is pending and duplicate enqueue keeps one command', async () => { const store = new MemoryNightclubOutboxStore(); const engine = new NightclubSyncEngine(store, { send: async () => ({ status: 'confirmed' }) }); await engine.enqueue(operation()); await engine.enqueue(operation()); assert.equal((await store.list(['pending'])).length, 1); assert.equal((await engine.summary(false)).state, 'offline') })
test('operation is confirmed only after server acknowledgement', async () => { const store = new MemoryNightclubOutboxStore(); let release; const ack = new Promise(resolve => { release = resolve }); const engine = new NightclubSyncEngine(store, { send: async () => { await ack; return { status: 'confirmed' } } }); await engine.enqueue(operation()); const syncing = engine.sync(true); await new Promise(resolve => setTimeout(resolve, 0)); assert.equal((await store.get('op-1')).status, 'syncing'); release(); await syncing; assert.equal((await store.get('op-1')).status, 'confirmed'); assert.equal((await store.get('op-1')).attempts, 1) })
test('network failure remains durable and retries same operationId', async () => { const store = new MemoryNightclubOutboxStore(); let calls = 0; const engine = new NightclubSyncEngine(store, { send: async row => { calls++; assert.equal(row.operationId, 'op-1'); if (calls === 1) throw new Error('offline'); return { status: 'confirmed' } } }); await engine.enqueue(operation()); assert.equal((await engine.sync(true)).state, 'attention'); assert.equal((await store.get('op-1')).status, 'failed'); await engine.sync(true); assert.equal((await store.get('op-1')).status, 'confirmed'); assert.equal((await store.get('op-1')).attempts, 2) })
test('business conflict requires attention and is not retried blindly', async () => { const store = new MemoryNightclubOutboxStore(); const engine = new NightclubSyncEngine(store, { send: async () => ({ status: 'conflict', message: 'La cuenta ya fue cobrada.' }) }); await engine.enqueue(operation()); const summary = await engine.sync(true); assert.equal(summary.state, 'attention'); assert.equal((await store.get('op-1')).status, 'conflict'); assert.match((await store.get('op-1')).lastError, /cobrada/) })
test('application confirms locally only after durable write', async () => { const store = new MemoryNightclubOutboxStore(); const client = new NightclubCommandClient(store, { tenantId: 'tenant-a', branchId: 'main', actorUid: 'waiter-a' }, () => 'local-op'); const accepted = await client.submit('requestBill', { accountId: 'account-1' }); assert.equal(accepted.status, 'pending'); assert.equal((await store.get('local-op')).operationId, 'local-op') })
test('gateway transport sends identity envelope and exposes business conflicts', async () => { let sent; const transport = createNightclubGatewayTransport(async payload => { sent = payload; throw Object.assign(new Error('La mesa está ocupada.'), { code: 'functions/aborted' }) }); const response = await transport.send(operation()); assert.equal(sent.action, 'nightclubCommand'); assert.equal(sent.tenantId, 'tenant-a'); assert.equal(response.status, 'conflict') })
