export type NightclubCommandType = 'openAccount' | 'addRound' | 'updateRoundStatus' | 'cancelRound' | 'requestBill' | 'reopenBill' | 'recordPayment' | 'inventoryMovement' | 'openShift' | 'closeShift' | 'courtesy' | 'void'
export type NightclubOperationStatus = 'pending' | 'syncing' | 'confirmed' | 'conflict' | 'failed'
export interface NightclubOutboxOperation<T = unknown> { operationId: string; tenantId: string; branchId: string; actorUid: string; type: NightclubCommandType; payload: T; createdAt: string; status: NightclubOperationStatus; attempts: number; lastError: string | null; confirmedAt?: string }
export interface NightclubOutboxStore { put(operation: NightclubOutboxOperation): Promise<void>; get(operationId: string): Promise<NightclubOutboxOperation | null>; list(statuses: NightclubOperationStatus[]): Promise<NightclubOutboxOperation[]>; patch(operationId: string, patch: Partial<NightclubOutboxOperation>): Promise<void> }
export interface NightclubCommandTransport { send(operation: NightclubOutboxOperation): Promise<{ status: 'confirmed' } | { status: 'conflict'; message: string }> }
export interface NightclubSyncSummary { pending: number; syncing: number; confirmed: number; conflict: number; failed: number; state: 'online' | 'offline' | 'syncing' | 'attention' }
export function createNightclubOperation<T>(input: Omit<NightclubOutboxOperation<T>, 'createdAt' | 'status' | 'attempts' | 'lastError'>, now = new Date().toISOString()): NightclubOutboxOperation<T> { if (!input.operationId || !input.tenantId || !input.branchId || !input.actorUid) throw new Error('La operación offline requiere identidades completas.'); return { ...input, createdAt: now, status: 'pending', attempts: 0, lastError: null } }
export class NightclubSyncEngine {
  private readonly store: NightclubOutboxStore
  private readonly transport: NightclubCommandTransport
  constructor(store: NightclubOutboxStore, transport: NightclubCommandTransport) { this.store = store; this.transport = transport }
  async enqueue<T>(operation: NightclubOutboxOperation<T>) { if (!await this.store.get(operation.operationId)) await this.store.put(operation) }
  async sync(online: boolean) { if (!online) return this.summary(false); for (const operation of await this.store.list(['pending', 'failed'])) { await this.store.patch(operation.operationId, { status: 'syncing', attempts: operation.attempts + 1, lastError: null }); try { const result = await this.transport.send({ ...operation, status: 'syncing', attempts: operation.attempts + 1 }); if (result.status === 'confirmed') await this.store.patch(operation.operationId, { status: 'confirmed', confirmedAt: new Date().toISOString() }); else await this.store.patch(operation.operationId, { status: 'conflict', lastError: result.message }) } catch (error) { await this.store.patch(operation.operationId, { status: 'failed', lastError: error instanceof Error ? error.message : 'Error de sincronización' }) } } return this.summary(true) }
  async summary(online: boolean): Promise<NightclubSyncSummary> { const rows = await this.store.list(['pending','syncing','confirmed','conflict','failed']); const count = (status: NightclubOperationStatus) => rows.filter(row => row.status === status).length; const result = { pending: count('pending'), syncing: count('syncing'), confirmed: count('confirmed'), conflict: count('conflict'), failed: count('failed') }; return { ...result, state: !online ? 'offline' : result.syncing ? 'syncing' : result.conflict || result.failed ? 'attention' : 'online' } }
}
export class MemoryNightclubOutboxStore implements NightclubOutboxStore { private readonly rows = new Map<string, NightclubOutboxOperation>(); async put(row: NightclubOutboxOperation) { this.rows.set(row.operationId, structuredClone(row)) } async get(id: string) { return structuredClone(this.rows.get(id) || null) } async list(statuses: NightclubOperationStatus[]) { return [...this.rows.values()].filter(row => statuses.includes(row.status)).sort((a,b) => a.createdAt.localeCompare(b.createdAt)).map(row => structuredClone(row)) } async patch(id: string, patch: Partial<NightclubOutboxOperation>) { const row = this.rows.get(id); if (!row) throw new Error('Operación local no encontrada.'); this.rows.set(id, { ...row, ...structuredClone(patch) }) } }
