import assert from 'node:assert/strict'
import { createRequire } from 'node:module'

const projectId = 'demo-pachax-platform'
if (process.env.GCLOUD_PROJECT && process.env.GCLOUD_PROJECT !== projectId) throw new Error('QA permitido solo en demo-pachax-platform.')
process.env.FIRESTORE_EMULATOR_HOST ||= '127.0.0.1:8185'
const require = createRequire(new URL('../../functions/package.json', import.meta.url))
const { initializeApp, deleteApp } = require('firebase-admin/app')
const { getFirestore } = require('firebase-admin/firestore')
const { getTemplate } = require('./generated/templates.js')
const { executeNightclubCommand } = require('./nightclub.cjs')
const suffix = Date.now().toString(36)
const tenantId = `orders_${suffix}`
const app = initializeApp({ projectId }, `nightclub-orders-${suffix}`)
const db = getFirestore(app)
const root = db.doc(`tenants/${tenantId}`)
const call = (uid, commandType, operationId, payload = {}) => executeNightclubCommand(db, { auth: { uid }, data: { tenantId, branchId: 'main', commandType, operationId, payload } })
const data = async path => (await root.collection(path.split('/')[0]).doc(path.split('/')[1]).get()).data()

try {
  const template = getTemplate('nightclub_lounge')
  await root.set({ tenantId, businessType: 'nightclub_lounge', configuration: template.defaults })
  for (const role of template.roles) await root.collection('roles').doc(role.id).set({ ...role, tenantId })
  for (const [uid, roleId] of [['waiter', 'waiter'], ['bar', 'bar'], ['admin', 'admin']]) await root.collection('members').doc(uid).set({ uid, tenantId, roleId, status: 'active', branchIds: ['main'] })
  await root.collection('nightclubOperationalState').doc('main').set({ activeShiftId: 'shift' })
  await root.collection('nightclubShifts').doc('shift').set({ id: 'shift', branchId: 'main', status: 'open', openingFloat: 0 })
  await root.collection('nightclubTables').doc('table').set({ branchId: 'main', status: 'occupied', activeAccountId: 'table-account' })
  await root.collection('nightclubAccounts').doc('table-account').set({ id: 'table-account', branchId: 'main', status: 'open', serviceTarget: { type: 'table', tableId: 'table' }, shiftId: 'shift', subtotal: 0, paidTotal: 0, balance: 0, roundCount: 0 })
  await root.collection('nightclubProducts').doc('ron').set({ branchId: 'main', name: 'Ron', active: true, price: 300, preparationArea: 'Barra', recipe: [{ inventoryId: 'ron-stock', quantity: 1 }] })
  await root.collection('nightclubInventory').doc('ron-stock').set({ branchId: 'main', name: 'Ron', current: 2 })
  const payload = { accountId: 'table-account', items: [{ productId: 'ron', quantity: 1 }], payment: { method: 'qr', amount: 300 } }
  await assert.rejects(() => call('waiter', 'addRound', 'legacy-unpaid', { accountId: 'table-account', items: payload.items }), error => error.code === 'invalid-argument')
  await root.collection('nightclubRounds').doc('unpaid-fixture').set({ id: 'unpaid-fixture', branchId: 'main', accountId: 'table-account', status: 'pending', items: payload.items })
  await assert.rejects(() => call('bar', 'advanceRound', 'unpaid-prepare', { accountId: 'table-account', roundId: 'unpaid-fixture' }), error => error.code === 'failed-precondition')
  await root.collection('nightclubRounds').doc('unpaid-fixture').delete()
  const [a, b] = await Promise.all([call('waiter', 'settleRound', 'sale-1', payload), call('waiter', 'settleRound', 'sale-1', payload)])
  assert.equal(a.roundId, 'round_sale-1'); assert.equal(b.roundId, 'round_sale-1')
  assert.equal((await data('nightclubInventory/ron-stock')).current, 1)
  assert.equal((await data('nightclubAccounts/table-account')).paidTotal, 300)
  assert.equal((await root.collection('nightclubPayments').get()).size, 1)
  assert.equal((await root.collection('nightclubRounds').get()).size, 1)
  assert.equal((await root.collection('nightclubInventoryMovements').get()).size, 1)
  console.log('PASS cobro atómico y reintento: un pago, una ronda, un descuento')
  await assert.rejects(() => call('waiter', 'settleRound', 'sale-1', { ...payload, payment: { method: 'cash', amount: 300 } }), error => error.code === 'already-exists')
  await assert.rejects(() => call('bar', 'settleRound', 'bar-sale', payload), error => error.code === 'permission-denied')
  await assert.rejects(() => call('waiter', 'advanceRound', 'bad-role', { accountId: 'table-account', roundId: a.roundId }), error => error.code === 'permission-denied')
  await call('bar', 'advanceRound', 'prepare-1', { accountId: 'table-account', roundId: a.roundId })
  await call('bar', 'advanceRound', 'ready-1', { accountId: 'table-account', roundId: a.roundId })
  await assert.rejects(() => call('waiter', 'deliverRound', 'bad-deliver', { accountId: 'table-account', roundId: a.roundId }), error => error.code === 'permission-denied')
  const beforeDelivery = { stock: (await data('nightclubInventory/ron-stock')).current, payments: (await root.collection('nightclubPayments').get()).size, movements: (await root.collection('nightclubInventoryMovements').get()).size }
  await call('bar', 'deliverRound', 'deliver-1', { accountId: 'table-account', roundId: a.roundId })
  await call('bar', 'deliverRound', 'deliver-1', { accountId: 'table-account', roundId: a.roundId })
  await assert.rejects(() => call('bar', 'deliverRound', 'deliver-2', { accountId: 'table-account', roundId: a.roundId }), error => error.code === 'failed-precondition')
  assert.equal((await data('nightclubRounds/round_sale-1')).status, 'delivered')
  assert.equal((await root.collection('nightclubPayments').get()).size, beforeDelivery.payments)
  assert.equal((await root.collection('nightclubInventoryMovements').get()).size, beforeDelivery.movements)
  assert.equal((await data('nightclubInventory/ron-stock')).current, beforeDelivery.stock)
  await call('waiter', 'finishOccupancy', 'close-1', { accountId: 'table-account' })
  assert.equal((await data('nightclubTables/table')).status, 'available')
  assert.equal((await data('nightclubAccounts/table-account')).paidTotal, 300)
  console.log('PASS entrega idempotente de Barra, sin segundo cobro ni stock; Servicio cierra mesa')
  await root.collection('nightclubAccounts').doc('refund-account').set({ id: 'refund-account', branchId: 'main', status: 'open', shiftId: 'shift', subtotal: 0, paidTotal: 0, balance: 0, roundCount: 0 })
  const competing = await Promise.allSettled(['race-a', 'race-b'].map(operationId => call('waiter', 'settleRound', operationId, { ...payload, accountId: 'refund-account' })))
  assert.equal(competing.filter(item => item.status === 'fulfilled').length, 1)
  const winner = competing.find(item => item.status === 'fulfilled').value.roundId
  assert.equal((await data('nightclubInventory/ron-stock')).current, 0)
  assert.equal((await data('nightclubAccounts/refund-account')).paidTotal, 300)
  console.log('PASS concurrencia: el último stock solo se vende una vez')
  await assert.rejects(() => call('waiter', 'refundRound', 'refund-denied', { accountId: 'refund-account', roundId: winner, reason: 'Pedido errado' }), error => error.code === 'permission-denied')
  const refunded = await call('admin', 'refundRound', 'refund-ok', { accountId: 'refund-account', roundId: winner, reason: 'Pedido errado' })
  assert.equal(refunded.status, 'refunded')
  assert.equal((await data('nightclubPayments/payment_' + winner.slice(6))).status, 'refunded')
  assert.equal((await data('nightclubInventory/ron-stock')).current, 1)
  assert.equal((await data('nightclubAccounts/refund-account')).paidTotal, 0)
  assert.equal((await root.collection('nightclubAudit').where('type', '==', 'refundRound').get()).size, 1)
  console.log('PASS reembolso restringido y auditado, caja y stock revertidos')
  await root.collection('nightclubProducts').doc('beer').set({ branchId: 'main', name: 'Cerveza', active: true, price: 25, preparationArea: 'Barra', recipe: [{ inventoryId: 'beer-stock', quantity: 1 }] })
  await root.collection('nightclubInventory').doc('beer-stock').set({ branchId: 'main', name: 'Cerveza', current: 2 })
  await assert.rejects(() => call('waiter', 'openAccount', 'bar-with-table', { target: { type: 'bar', tableId: 'table' } }), error => error.code === 'invalid-argument')
  const anonymous = await call('waiter', 'openAccount', 'bar-anonymous', { target: { type: 'bar' } })
  assert.deepEqual((await data(`nightclubAccounts/${anonymous.accountId}`)).serviceTarget, { type: 'bar' })
  assert.equal((await data(`nightclubAccounts/${anonymous.accountId}`)).orderType, 'BAR')
  const cashSale = await call('waiter', 'settleRound', 'bar-cash', { accountId: anonymous.accountId, items: [{ productId: 'beer', quantity: 1 }], payment: { method: 'cash', amount: 25 } })
  assert.equal((await data(`nightclubPayments/${cashSale.paymentId}`)).amount, 25)
  assert.equal((await data(`nightclubRounds/${cashSale.roundId}`)).authorization, 'payment')
  assert.equal((await data('nightclubInventory/beer-stock')).current, 1)
  assert.equal((await root.collection('nightclubCashMovements').where('accountId', '==', anonymous.accountId).get()).size, 1)
  const named = await call('waiter', 'openAccount', 'bar-juan', { target: { type: 'bar', displayName: 'Juan' } })
  assert.equal((await data(`nightclubAccounts/${named.accountId}`)).serviceTarget.displayName, 'Juan')
  const qrSale = await call('waiter', 'settleRound', 'bar-qr', { accountId: named.accountId, items: [{ productId: 'beer', quantity: 1 }], payment: { method: 'qr', amount: 25 } })
  assert.equal((await data(`nightclubPayments/${qrSale.paymentId}`)).method, 'qr')
  assert.equal((await data(`nightclubRounds/${qrSale.roundId}`)).status, 'pending')
  assert.equal((await data(`nightclubRounds/${qrSale.roundId}`)).tableId, null)
  assert.equal((await data(`nightclubAccounts/${named.accountId}`)).tableId, undefined)
  assert.equal((await data('nightclubAccounts/table-account')).paidTotal, 300)
  assert.equal((await root.collection('nightclubCustomers').get()).size, 0)
  assert.equal((await data('nightclubTables/table')).status, 'available')
  console.log('PASS pedido en barra anónimo y con nombre: cobro, Barra e inventario sin cliente ficticio')
  await root.collection('nightclubOperationalState').doc('main').set({ activeShiftId: 'cash-close' })
  await root.collection('nightclubShifts').doc('cash-close').set({ id: 'cash-close', branchId: 'main', status: 'open', openingFloat: 200 })
  for (const [index, countedCash] of [undefined, 0, 50, 199].entries()) {
    await assert.rejects(() => call('admin', 'closeShift', `cash-mismatch-${index}`, { shiftId: 'cash-close', countedCash }), error => ['invalid-argument', 'failed-precondition'].includes(error.code))
    assert.equal((await data('nightclubShifts/cash-close')).status, 'open')
  }
  const closed = await call('admin', 'closeShift', 'cash-match', { shiftId: 'cash-close', countedCash: 200 })
  assert.equal(closed.countedCash, 200)
  assert.equal((await data('nightclubShifts/cash-close')).status, 'closed')
  assert.equal((await data('nightclubShifts/cash-close')).countedCash, 200)
  assert.equal((await data('nightclubShifts/cash-close')).reconciliationStatus, 'balanced')
  assert.equal((await data('nightclubShifts/cash-close')).difference, 0)
  assert.equal((await data('nightclubOperationalState/main')).activeShiftId, null)
  assert.equal((await root.collection('nightclubAudit').where('type', '==', 'closeShift').get()).size, 1)
  assert.deepEqual(await call('admin', 'closeShift', 'cash-match', { shiftId: 'cash-close', countedCash: 200 }), closed)
  await root.collection('nightclubOperationalState').doc('main').set({ activeShiftId: 'cash-with-sale' })
  await root.collection('nightclubShifts').doc('cash-with-sale').set({ id: 'cash-with-sale', branchId: 'main', status: 'open', openingFloat: 200 })
  await root.collection('nightclubCashMovements').doc('cash-close-sale').set({ shiftId: 'cash-with-sale', branchId: 'main', type: 'sale', amount: 25 })
  await root.collection('nightclubPayments').doc('cash-close-payment').set({ shiftId: 'cash-with-sale', branchId: 'main', status: 'confirmed', amount: 25 })
  await assert.rejects(() => call('admin', 'closeShift', 'cash-sale-mismatch', { shiftId: 'cash-with-sale', countedCash: 200 }), error => error.code === 'failed-precondition')
  await call('admin', 'closeShift', 'cash-sale-surplus', { shiftId: 'cash-with-sale', countedCash: 227 })
  const surplusShift = await data('nightclubShifts/cash-with-sale')
  assert.equal(surplusShift.countedCash, 227)
  assert.equal(surplusShift.expectedCash, 225)
  assert.equal(surplusShift.difference, 2)
  assert.equal(surplusShift.reconciliationStatus, 'surplus')
  assert.equal(surplusShift.totalSales, 25)
  assert.equal(surplusShift.incomeTotal, 0)
  assert.equal((await root.collection('nightclubAudit').where('type', '==', 'closeShift').get()).size, 2)
  console.log('PASS cierre de turno: faltante rechazado, cuadrado o sobrante permitido y auditado')
} finally {
  await deleteApp(app)
}
