import { useState } from 'react'
import { Lock, Unlock, Wallet } from 'lucide-react'
import type { Order } from '../../types'
import type { RestaurantTable } from '../mocks/restaurantMock'

type Shift = { id: string; openedAt: string; openedBy: string; openingFloat: number; closedAt?: string }
const money = (amount: number) => `Bs ${amount.toLocaleString('es-BO', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`

export function RestaurantCash({ shift, orders, tables, userName, onStartShift, onCloseShift }: { shift: Shift | null; orders: Order[]; tables: RestaurantTable[]; userName: string; onStartShift: (amount: number, at: string, by: string) => void; onCloseShift: () => boolean }) {
  const [opening, setOpening] = useState('')
  const [closed, setClosed] = useState(false)
  const sales = orders.filter((order) => order.shiftId === shift?.id && order.paymentStatus === 'paid')
  const cash = sales.reduce((sum, order) => sum + (order.payment?.cashAmount || 0), 0)
  const other = sales.reduce((sum, order) => sum + (order.total - (order.payment?.cashAmount || 0)), 0)
  const total = sales.reduce((sum, order) => sum + order.total, 0)
  const openTables = tables.filter((table) => table.activeOrderId && table.status !== 'available')

  return <div className="mx-auto max-w-4xl space-y-6"><header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold text-slate-900">Caja & Control de Turnos</h1><p className="text-sm text-slate-500">Saldo, pagos y cierre del turno activo</p></div><span className={`inline-flex items-center gap-1 rounded-full px-3 py-1 text-xs font-bold ${shift ? 'bg-emerald-100 text-emerald-800' : 'bg-slate-100 text-slate-700'}`}>{shift ? <Unlock className="h-3.5 w-3.5" /> : <Lock className="h-3.5 w-3.5" />}{shift ? 'Turno Activo' : 'Turno Cerrado'}</span></header>
    {shift ? <><div className="grid grid-cols-1 gap-4 sm:grid-cols-3"><Summary label="Fondo inicial" amount={shift.openingFloat} /><Summary label="Ventas en efectivo" amount={cash} /><Summary label="Otros métodos" amount={other} /></div><div className="flex items-center justify-between rounded-2xl bg-gradient-to-r from-slate-900 to-slate-800 p-5 text-white"><div><span className="text-xs font-semibold uppercase tracking-wide text-slate-300">Efectivo esperado en gaveta</span><span className="mt-1 block text-3xl font-extrabold">{money(shift.openingFloat + cash)}</span></div><Wallet className="h-10 w-10 text-teal-400" /></div><section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="grid grid-cols-2 gap-3 text-sm"><div><span className="text-slate-500">Ventas totales</span><p className="mt-1 font-bold">{money(total)}</p></div><div><span className="text-slate-500">Pedidos pagados</span><p className="mt-1 font-bold">{sales.length}</p></div><div><span className="text-slate-500">Apertura</span><p className="mt-1 font-bold">{new Date(shift.openedAt).toLocaleString('es-BO')}</p></div><div><span className="text-slate-500">Responsable</span><p className="mt-1 font-bold">{shift.openedBy}</p></div></div></section><button onClick={() => { if (!openTables.length && onCloseShift()) setClosed(true) }} disabled={openTables.length > 0} className="rounded-xl bg-slate-900 px-5 py-3 text-sm font-bold text-white disabled:opacity-40">Cerrar turno</button>{openTables.length > 0 && <p className="text-sm text-amber-800">No puedes cerrar el turno mientras existan cuentas abiertas.</p>}{closed && <p role="status" className="text-sm font-semibold text-emerald-700">Turno cerrado correctamente.</p>}</> : <section className="rounded-2xl border border-slate-200 bg-white p-5"><p className="mb-4 text-sm text-slate-600">Debes iniciar un turno antes de realizar operaciones.</p><label className="block text-xs font-semibold">Fondo inicial / cambio en caja<input type="number" min="0" step="0.01" value={opening} onChange={(event) => setOpening(event.target.value)} placeholder="Bs 300,00" className="mt-1.5 w-full rounded-lg border border-slate-200 px-3 py-2 text-sm" /></label><button onClick={() => { const value = Number(opening); if (opening && Number.isFinite(value) && value >= 0) onStartShift(value, new Date().toISOString(), userName) }} className="mt-3 w-full rounded-xl bg-teal-500 py-3 text-sm font-bold text-slate-950">Confirmar e iniciar turno</button></section>}</div>
}
function Summary({ label, amount }: { label: string; amount: number }) { return <div className="rounded-xl border border-slate-200 bg-white p-4"><span className="text-xs font-semibold uppercase text-slate-500">{label}</span><span className="mt-1 block text-xl font-bold text-slate-900">{money(amount)}</span></div> }
