import { useState } from 'react'
import { AlertTriangle, ArrowDown, ArrowDownRight, ArrowUp, ArrowUpRight, Boxes, ChevronRight, CircleOff, MoreHorizontal, Package, Pencil, Plus, Search, SlidersHorizontal, Wallet, X } from 'lucide-react'
import { Modal } from '../../components/ui/Modal'
import { Field, NumberInput, SelectInput, TextInput } from '../../components/ui/Form'
import type { CatalogCategory, Product } from '../../types'
import type { RestaurantShift } from '../../modules/restaurant/views/RestaurantExperience'
import { convertInventoryQuantity, inventoryShiftRows, type InventoryMovement, type InventoryMovementType } from '../../modules/restaurant/domain/inventoryEngine'

type ManualType = Exclude<InventoryMovementType, 'sale' | 'cancellation_return' | 'command_consumption' | 'migration_reconciliation'>
type StockState = 'all' | 'normal' | 'low' | 'out' | 'inactive' | 'replenish'
type SortKey = 'name' | 'category' | 'stock' | 'minimum' | 'status'
type FormErrors = Partial<Record<'name' | 'stock' | 'minimum' | 'cost', string>>
type Props = {
  products: Product[]
  catalogCategories: CatalogCategory[]
  shift: RestaurantShift | null
  movements: InventoryMovement[]
  onSaveProducts: (products: Product[]) => void
  onInventoryMovement?: (productId: string, nextStock: number, type: ManualType, reason: string) => { ok: boolean; error?: string }
}

const movementNames: Record<InventoryMovementType, string> = { sale: 'Venta', cancellation_return: 'Cancelación', manual_adjustment: 'Ajuste', migration_reconciliation: 'Reconciliación local', purchase: 'Compra / entrada', waste: 'Merma', loss: 'Pérdida', courtesy: 'Cortesía', internal_consumption: 'Consumo interno', initial_stock: 'Stock inicial', command_consumption: 'Venta (legado)' }
const number = (value: number) => value.toLocaleString('es-BO', { maximumFractionDigits: 3 })
const money = (value: number) => `Bs ${value.toLocaleString('es-BO', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
const unitName = (unit?: Product['baseUnit'], label?: string) => unit === 'g' ? 'g' : unit === 'ml' ? 'ml' : label?.trim() || 'unid.'
const stockText = (item: Product) => `${number(item.stockBase || 0)} ${unitName(item.baseUnit, item.stockUnitLabel)}`
const stockState = (item: Product): Exclude<StockState, 'all' | 'replenish'> => item.isActive === false ? 'inactive' : (item.stockBase || 0) <= 0 ? 'out' : (item.stockBase || 0) <= (item.minimumStockBase || 0) ? 'low' : 'normal'
const stateName: Record<Exclude<StockState, 'all' | 'replenish'>, string> = { normal: 'Normal', low: 'Stock bajo', out: 'Sin stock', inactive: 'Desactivado' }
const blankProduct = (count: number): Product => ({ id: '', name: '', categoryId: 'cat-insumos', description: 'General', price: 0, image: '', availability: 'available', sortOrder: count, isActive: true, isVisible: false, restaurantType: 'ingredient', baseUnit: 'unit', stockBase: 0, minimumStockBase: 0, unitCost: 0 })
const inputClass = 'min-h-11 min-w-0 rounded-xl border border-slate-200 bg-white px-3 text-sm text-slate-800 outline-none transition focus:border-teal-500 focus:ring-2 focus:ring-teal-100'

function StatusBadge({ state }: { state: ReturnType<typeof stockState> }) {
  const colors = { normal: 'bg-emerald-50 text-emerald-800', low: 'bg-amber-50 text-amber-900', out: 'bg-rose-50 text-rose-800', inactive: 'bg-slate-100 text-slate-600' }
  return <span className={`inline-flex rounded-full px-2.5 py-1 text-[11px] font-bold ${colors[state]}`}>{stateName[state]}</span>
}

function StockLevel({ item }: { item: Product }) {
  const minimum = item.minimumStockBase || 0
  if (minimum <= 0 || item.isActive === false) return null
  const state = stockState(item)
  const width = Math.min(100, Math.max(0, ((item.stockBase || 0) / (minimum * 2)) * 100))
  return <div className="ml-auto mt-1.5 h-1.5 w-28 max-w-full overflow-hidden rounded-full bg-slate-100" title={`Mínimo: ${number(minimum)} ${unitName(item.baseUnit, item.stockUnitLabel)}`}><div className={`h-full rounded-full ${state === 'out' ? 'bg-rose-500' : state === 'low' ? 'bg-amber-500' : 'bg-emerald-500'}`} style={{ width: `${width}%` }} /></div>
}

function MovementBadge({ type }: { type: InventoryMovementType }) {
  const positive = ['purchase', 'initial_stock', 'cancellation_return'].includes(type)
  const neutral = ['manual_adjustment', 'migration_reconciliation'].includes(type)
  return <span className={`inline-flex items-center gap-1 rounded-full px-2 py-1 text-[11px] font-bold ${neutral ? 'bg-slate-100 text-slate-700' : positive ? 'bg-emerald-50 text-emerald-800' : 'bg-amber-50 text-amber-900'}`}>{positive ? <ArrowDownRight size={13} /> : neutral ? <SlidersHorizontal size={13} /> : <ArrowUpRight size={13} />}{movementNames[type]}</span>
}

export function RestaurantInventory({ products, catalogCategories, shift, movements, onSaveProducts, onInventoryMovement }: Props) {
  const items = products.filter(item => item.stockBase !== undefined)
  const [view, setView] = useState<'current' | 'movements'>('current')
  const [query, setQuery] = useState('')
  const [category, setCategory] = useState('all')
  const [statusFilter, setStatusFilter] = useState<StockState>('all')
  const [sort, setSort] = useState<{ key: SortKey; direction: 'asc' | 'desc' }>({ key: 'name', direction: 'asc' })
  const [typeFilter, setTypeFilter] = useState('all')
  const [productFilter, setProductFilter] = useState('all')
  const [shiftFilter, setShiftFilter] = useState('all')
  const [userFilter, setUserFilter] = useState('all')
  const [dateFilter, setDateFilter] = useState('')
  const [editing, setEditing] = useState<Product | null>(null)
  const [removing, setRemoving] = useState<Product | null>(null)
  const [form, setForm] = useState<Product>(blankProduct(products.length))
  const [formErrors, setFormErrors] = useState<FormErrors>({})
  const [newCategory, setNewCategory] = useState(false)
  const [selectedId, setSelectedId] = useState<string | null>(null)
  const [menu, setMenu] = useState<string | null>(null)
  const [movementProduct, setMovementProduct] = useState<Product | null>(null)
  const [movementType, setMovementType] = useState<ManualType>('purchase')
  const [movementAmount, setMovementAmount] = useState('')
  const [movementUnit, setMovementUnit] = useState<'unit' | 'g' | 'kg' | 'ml' | 'l'>('unit')
  const [reason, setReason] = useState('')
  const [movementError, setMovementError] = useState('')
  const [notice, setNotice] = useState('')

  const categoryName = (item: Product) => item.restaurantType === 'ingredient' ? item.description || 'General' : catalogCategories.find(value => value.id === item.categoryId)?.name || item.description || 'General'
  const categories = [...new Set(items.map(categoryName))].sort((a, b) => a.localeCompare(b, 'es'))
  const shiftRows = shift ? inventoryShiftRows(products, shift.stockSnapshot || {}, movements, shift.id, shift.inventoryCounts) : []
  const shiftById = new Map(shiftRows.map(row => [row.productId, row]))
  const byId = new Map(products.map(item => [item.id, item]))
  const selected = selectedId ? byId.get(selectedId) : null
  const active = items.filter(item => item.isActive !== false)
  const low = active.filter(item => stockState(item) === 'low')
  const out = active.filter(item => stockState(item) === 'out')
  const withoutCost = items.filter(item => item.unitCost === undefined || !Number.isFinite(item.unitCost))
  const inventoryValue = items.reduce((total, item) => total + (Number.isFinite(item.unitCost) ? (item.stockBase || 0) * (item.unitCost || 0) : 0), 0)
  const normalizedQuery = query.trim().toLocaleLowerCase('es-BO')
  const shown = items.filter(item => {
    const state = stockState(item)
    return (category === 'all' || categoryName(item) === category) && (statusFilter === 'all' || statusFilter === state || (statusFilter === 'replenish' && (state === 'low' || state === 'out'))) && (!normalizedQuery || `${item.name} ${categoryName(item)} ${unitName(item.baseUnit, item.stockUnitLabel)} ${item.baseUnit || ''}`.toLocaleLowerCase('es-BO').includes(normalizedQuery))
  }).sort((a, b) => {
    const left = sort.key === 'name' ? a.name : sort.key === 'category' ? categoryName(a) : sort.key === 'stock' ? a.stockBase || 0 : sort.key === 'minimum' ? a.minimumStockBase || 0 : ['out', 'low', 'normal', 'inactive'].indexOf(stockState(a))
    const right = sort.key === 'name' ? b.name : sort.key === 'category' ? categoryName(b) : sort.key === 'stock' ? b.stockBase || 0 : sort.key === 'minimum' ? b.minimumStockBase || 0 : ['out', 'low', 'normal', 'inactive'].indexOf(stockState(b))
    const comparison = typeof left === 'string' && typeof right === 'string' ? left.localeCompare(right, 'es', { sensitivity: 'base' }) : Number(left) - Number(right)
    return (comparison || a.name.localeCompare(b.name, 'es')) * (sort.direction === 'asc' ? 1 : -1)
  })
  const shownMovements = movements.filter(item => {
    const product = byId.get(item.productId)
    const matchesQuery = `${item.productName || product?.name || ''} ${item.orderId || ''} ${item.createdBy || ''} ${item.reason || ''} ${movementNames[item.type]}`.toLocaleLowerCase('es-BO').includes(normalizedQuery)
    return (typeFilter === 'all' || item.type === typeFilter) && (productFilter === 'all' || item.productId === productFilter) && (shiftFilter === 'all' || item.shiftId === shiftFilter) && (userFilter === 'all' || item.createdBy === userFilter) && (!dateFilter || item.createdAt.slice(0, 10) === dateFilter) && (category === 'all' || (product ? categoryName(product) : 'General') === category) && matchesQuery
  }).sort((a, b) => b.createdAt.localeCompare(a.createdAt))

  const chooseStatus = (next: StockState) => { setView('current'); setStatusFilter(next); if (next === 'all' || next === 'replenish') { setQuery(''); setCategory('all') } }
  const chooseSort = (key: SortKey) => setSort(previous => ({ key, direction: previous.key === key && previous.direction === 'asc' ? 'desc' : 'asc' }))
  const openProduct = (product?: Product) => { const next = product || blankProduct(products.length); setForm(next); setFormErrors({}); setNewCategory(false); setEditing(next); setMenu(null) }
  const openMovement = (product: Product) => { setMovementProduct(product); setMovementType('purchase'); setMovementAmount(''); setMovementUnit(product.baseUnit || 'unit'); setReason(''); setMovementError(''); setMenu(null) }
  const saveProduct = () => {
    const errors: FormErrors = {}
    if (!form.name.trim()) errors.name = 'El nombre es obligatorio.'
    if (!Number.isFinite(form.stockBase) || (form.stockBase || 0) < 0) errors.stock = 'El stock no puede ser negativo.'
    if (!Number.isFinite(form.minimumStockBase) || (form.minimumStockBase || 0) < 0) errors.minimum = 'El stock mínimo no puede ser negativo.'
    if (form.unitCost !== undefined && (!Number.isFinite(form.unitCost) || form.unitCost < 0)) errors.cost = 'Ingresa un costo válido.'
    setFormErrors(errors)
    if (Object.keys(errors).length) return
    const typedCategory = form.description?.trim() || 'General'
    const canonicalCategory = categories.find(name => name.toLocaleLowerCase('es-BO') === typedCategory.toLocaleLowerCase('es-BO')) || typedCategory
    const next = { ...form, id: form.id || crypto.randomUUID(), name: form.name.trim(), description: canonicalCategory }
    const stockChanged = !!form.id && products.some(item => item.id === form.id && item.stockBase !== next.stockBase)
    onSaveProducts(form.id ? products.map(item => item.id === next.id ? next : item) : [...products, next])
    setEditing(null)
    setNotice(form.id ? stockChanged ? 'Insumo actualizado. El cambio de stock quedó registrado.' : 'Insumo actualizado correctamente.' : 'Insumo creado con stock inicial registrado.')
  }
  const saveMovement = () => {
    if (!movementProduct || !onInventoryMovement) return
    try {
      const amount = convertInventoryQuantity(Number(movementAmount), movementUnit, movementProduct.baseUnit)
      if (movementAmount === '' || (amount <= 0 && movementType !== 'manual_adjustment')) throw new Error('Ingresa una cantidad mayor a cero.')
      const nextStock = movementType === 'manual_adjustment' ? amount : (movementProduct.stockBase || 0) + (['purchase', 'initial_stock'].includes(movementType) ? amount : -amount)
      const result = onInventoryMovement(movementProduct.id, nextStock, movementType, reason)
      if (!result.ok) throw new Error(result.error || 'No se pudo registrar el movimiento.')
      setMovementProduct(null)
      setNotice('Movimiento registrado y stock actualizado.')
    } catch (error) { setMovementError(error instanceof Error ? error.message : 'Cantidad inválida.') }
  }
  const activate = (item: Product) => { onSaveProducts(products.map(value => value.id === item.id ? { ...value, isActive: true, isVisible: value.restaurantType === 'ingredient' ? false : true } : value)); setNotice(`${item.name} activado.`); setMenu(null) }
  const actions = (item: Product) => <div className="relative flex items-center gap-1" onClick={event => event.stopPropagation()}>
    <button type="button" onClick={() => openMovement(item)} className="inline-flex min-h-10 items-center gap-1 rounded-lg px-2 text-xs font-bold text-teal-700 transition hover:bg-teal-50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-teal-600"><Plus size={14} />Movimiento</button>
    <button type="button" aria-label={`Más acciones de ${item.name}`} aria-expanded={menu === item.id} onClick={() => setMenu(menu === item.id ? null : item.id)} className="rounded-lg p-2 text-slate-500 transition hover:bg-slate-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-teal-600"><MoreHorizontal size={18} /></button>
    {menu === item.id && <div className="absolute right-0 top-10 z-20 grid min-w-32 rounded-xl border border-slate-200 bg-white p-1 shadow-lg"><button type="button" onClick={() => openProduct(item)} className="flex items-center gap-2 rounded-lg p-2 text-left text-xs hover:bg-slate-50"><Pencil size={13} />Editar</button>{item.isActive === false ? <button type="button" onClick={() => activate(item)} className="rounded-lg p-2 text-left text-xs text-emerald-700 hover:bg-emerald-50">Activar</button> : <button type="button" onClick={() => { setRemoving(item); setMenu(null) }} className="rounded-lg p-2 text-left text-xs text-rose-700 hover:bg-rose-50">Desactivar</button>}</div>}
  </div>
  const sortButton = (label: string, key: SortKey) => <button type="button" onClick={() => chooseSort(key)} aria-label={`Ordenar por ${label}`} className="inline-flex items-center gap-1 hover:text-slate-900 focus-visible:outline focus-visible:outline-2 focus-visible:outline-teal-600">{label}{sort.key === key ? sort.direction === 'asc' ? <ArrowUp size={13} /> : <ArrowDown size={13} /> : null}</button>

  return <div className="mx-auto max-w-6xl space-y-5 pb-8 text-slate-900">
    <header className="flex flex-wrap items-start justify-between gap-3"><div><p className="mb-1 text-[11px] font-extrabold uppercase tracking-[0.18em] text-teal-700">Operación y reposición</p><h1 className="text-2xl font-extrabold tracking-tight sm:text-3xl">Inventario</h1><p className="mt-1 text-sm text-slate-500">Stock teórico y movimientos vinculados a pedidos y turnos.</p></div><button type="button" onClick={() => openProduct()} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-slate-900 px-4 text-sm font-bold text-white transition hover:bg-slate-800 focus-visible:outline focus-visible:outline-2 focus-visible:outline-teal-600"><Plus size={16} />Nuevo insumo</button></header>
    {notice && <p role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm font-semibold text-emerald-800">{notice}</p>}
    <section aria-label="Resumen de inventario" className="grid grid-cols-2 gap-3 lg:grid-cols-4">
      <SummaryCard label="Total insumos" value={String(items.length)} icon={Boxes} active={view === 'current' && statusFilter === 'all'} onClick={() => chooseStatus('all')} />
      <SummaryCard label="Stock bajo" value={String(low.length)} icon={AlertTriangle} active={view === 'current' && statusFilter === 'low'} onClick={() => chooseStatus('low')} tone="amber" />
      <SummaryCard label="Sin stock" value={String(out.length)} icon={CircleOff} active={view === 'current' && statusFilter === 'out'} onClick={() => chooseStatus('out')} tone="rose" />
      <div className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex items-center justify-between gap-2"><span className="text-[11px] font-bold uppercase tracking-wide text-slate-600">Valor inventario</span><Wallet size={18} className="text-slate-400" /></div><strong className="mt-2 block text-xl font-extrabold tabular-nums tracking-tight">{money(inventoryValue)}</strong><p className="mt-1 text-[11px] text-slate-500">{withoutCost.length ? `Estimado · ${withoutCost.length} sin costo registrado` : 'Stock × costo por unidad base'}</p></div>
    </section>
    {low.length + out.length > 0 && <div className="flex flex-wrap items-center justify-between gap-2 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900"><span className="inline-flex items-center gap-2 font-semibold"><AlertTriangle size={17} />{low.length + out.length} {low.length + out.length === 1 ? 'insumo necesita' : 'insumos necesitan'} reposición</span><button type="button" onClick={() => chooseStatus('replenish')} className="text-xs font-bold underline underline-offset-2 focus-visible:outline focus-visible:outline-2 focus-visible:outline-amber-700">Ver insumos <ChevronRight size={13} className="inline" /></button></div>}
    <div className="flex gap-1 border-b border-slate-200" role="tablist" aria-label="Secciones de inventario">{([['current', 'Inventario actual'], ['movements', 'Movimientos']] as const).map(([id, title]) => <button key={id} type="button" role="tab" aria-selected={view === id} onClick={() => setView(id)} className={`border-b-2 px-4 py-2.5 text-sm font-bold transition ${view === id ? 'border-teal-600 text-slate-900' : 'border-transparent text-slate-500 hover:text-slate-800'}`}>{title}</button>)}</div>
    <div className="flex flex-wrap gap-2"><label className="relative min-w-48 flex-1"><Search size={16} className="pointer-events-none absolute left-3 top-3.5 text-slate-400" /><span className="sr-only">Buscar {view === 'current' ? 'insumos' : 'movimientos'}</span><input type="search" value={query} onChange={event => setQuery(event.target.value)} placeholder={view === 'current' ? 'Buscar insumo, categoría o unidad' : 'Buscar producto, pedido, usuario o motivo'} className={`${inputClass} w-full pl-9`} /></label><select value={category} onChange={event => setCategory(event.target.value)} aria-label="Categoría" className={inputClass}><option value="all">Todas las categorías</option>{categories.map(name => <option key={name} value={name}>{name}</option>)}</select>{view === 'current' && <select value={statusFilter} onChange={event => setStatusFilter(event.target.value as StockState)} aria-label="Estado de stock" className={inputClass}><option value="all">Todos los estados</option><option value="normal">Normal</option><option value="low">Stock bajo</option><option value="out">Sin stock</option><option value="inactive">Desactivado</option><option value="replenish">Necesitan reposición</option></select>}</div>
    {view === 'current' ? <section aria-label="Inventario actual">
      {shown.length ? <><div className="hidden overflow-x-auto rounded-2xl border border-slate-200 bg-white md:block"><table className="w-full min-w-[840px] text-left text-sm"><thead className="sticky top-0 z-10 bg-slate-50 text-[11px] uppercase tracking-wide text-slate-500"><tr><th className="px-3 py-3">{sortButton('Producto', 'name')}</th><th className="px-3 py-3">{sortButton('Categoría', 'category')}</th><th className="px-3 py-3 text-right">{sortButton('Stock actual', 'stock')}</th><th className="px-3 py-3 text-right">{sortButton('Mínimo', 'minimum')}</th><th className="px-3 py-3 text-right">Turno</th><th className="px-3 py-3">{sortButton('Estado', 'status')}</th><th className="px-3 py-3">Acciones</th></tr></thead><tbody className="divide-y divide-slate-100">{shown.map(item => { const row = shiftById.get(item.id); return <tr key={item.id} className="cursor-pointer transition-colors hover:bg-slate-50" onClick={() => setSelectedId(item.id)}><td className="px-3 py-2.5 font-semibold"><button type="button" onClick={() => setSelectedId(item.id)} className="text-left hover:text-teal-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-teal-600">{item.name}</button></td><td className="px-3 py-2.5 text-slate-600">{categoryName(item)}</td><td className="px-3 py-2.5 text-right"><strong className="tabular-nums">{stockText(item)}</strong><StockLevel item={item} /></td><td className="px-3 py-2.5 text-right tabular-nums text-slate-600">{number(item.minimumStockBase || 0)} {unitName(item.baseUnit, item.stockUnitLabel)}</td><td className="px-3 py-2.5 text-right tabular-nums text-slate-600">{row ? `${number(row.sales + row.returns + row.incoming + row.waste + row.adjustments)} ${unitName(item.baseUnit, item.stockUnitLabel)}` : '—'}</td><td className="px-3 py-2.5"><StatusBadge state={stockState(item)} /></td><td className="px-3 py-2.5">{actions(item)}</td></tr> })}</tbody></table></div>
      <div className="space-y-2 md:hidden">{shown.map(item => <div key={item.id} className="rounded-2xl border border-slate-200 bg-white p-3"><button type="button" onClick={() => setSelectedId(item.id)} className="flex w-full items-start justify-between gap-2 text-left"><span className="min-w-0"><strong className="block break-words text-sm">{item.name}</strong><span className="text-xs text-slate-500">{categoryName(item)}</span></span><StatusBadge state={stockState(item)} /></button><div className="mt-3 flex items-end justify-between gap-3"><div><span className="text-[11px] text-slate-500">Stock actual</span><strong className="block text-lg tabular-nums">{stockText(item)}</strong><StockLevel item={item} /><span className="mt-1 block text-xs text-slate-500">Mínimo {number(item.minimumStockBase || 0)} {unitName(item.baseUnit, item.stockUnitLabel)}</span></div>{actions(item)}</div></div>)}</div></> : <EmptyInventory filtered={items.length > 0} />}
    </section> : <section aria-label="Movimientos de inventario" className="space-y-3">
      <div className="flex flex-wrap gap-2"><input type="date" aria-label="Fecha" value={dateFilter} onChange={event => setDateFilter(event.target.value)} className={inputClass} /><select aria-label="Producto" value={productFilter} onChange={event => setProductFilter(event.target.value)} className={inputClass}><option value="all">Todos los productos</option>{items.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select aria-label="Turno" value={shiftFilter} onChange={event => setShiftFilter(event.target.value)} className={inputClass}><option value="all">Todos los turnos</option>{[...new Set(movements.map(item => item.shiftId).filter(Boolean))].map(id => <option key={id} value={id}>{id}</option>)}</select><select aria-label="Tipo de movimiento" value={typeFilter} onChange={event => setTypeFilter(event.target.value)} className={inputClass}><option value="all">Todos los tipos</option>{Object.entries(movementNames).map(([id, title]) => <option key={id} value={id}>{title}</option>)}</select><select aria-label="Usuario" value={userFilter} onChange={event => setUserFilter(event.target.value)} className={inputClass}><option value="all">Todos los usuarios</option>{[...new Set(movements.map(item => item.createdBy).filter(Boolean))].map(name => <option key={name} value={name}>{name}</option>)}</select></div>
      {shownMovements.length ? <><div className="hidden overflow-x-auto rounded-2xl border border-slate-200 bg-white md:block"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-[11px] uppercase tracking-wide text-slate-500"><tr><th className="px-3 py-3">Cuándo</th><th className="px-3 py-3">Insumo</th><th className="px-3 py-3">Tipo</th><th className="px-3 py-3 text-right">Cambio</th><th className="px-3 py-3 text-right">Stock</th><th className="px-3 py-3">Origen / motivo</th><th className="px-3 py-3">Usuario</th></tr></thead><tbody className="divide-y divide-slate-100">{shownMovements.map(item => <tr key={item.id} className="transition-colors hover:bg-slate-50"><td className="whitespace-nowrap px-3 py-2.5 text-xs text-slate-600">{new Date(item.createdAt).toLocaleString('es-BO', { dateStyle: 'short', timeStyle: 'short' })}</td><td className="px-3 py-2.5 font-semibold">{item.productName || byId.get(item.productId)?.name || item.productId}</td><td className="px-3 py-2.5"><MovementBadge type={item.type} /></td><td className={`whitespace-nowrap px-3 py-2.5 text-right font-bold tabular-nums ${item.quantityBase < 0 ? 'text-rose-700' : 'text-emerald-700'}`}>{item.quantityBase > 0 ? '+' : item.quantityBase < 0 ? '−' : ''}{number(Math.abs(item.quantityBase))} {unitName(byId.get(item.productId)?.baseUnit, byId.get(item.productId)?.stockUnitLabel)}</td><td className="whitespace-nowrap px-3 py-2.5 text-right text-xs tabular-nums">{item.previousStock === undefined ? '—' : `${number(item.previousStock)} → ${number(item.newStock ?? 0)}`}</td><td className="px-3 py-2.5 text-xs text-slate-600">{item.tableId ? `Mesa ${item.tableId} · ` : ''}{item.orderId ? `Pedido ${item.orderId} · ` : ''}{item.reason || 'Manual'}</td><td className="px-3 py-2.5 text-xs text-slate-600">{item.createdBy || 'Legado'}</td></tr>)}</tbody></table></div>
      <div className="space-y-2 md:hidden">{shownMovements.map(item => <MovementCard key={item.id} item={item} product={byId.get(item.productId)} />)}</div></> : <div className="rounded-2xl border border-dashed border-slate-200 bg-white px-4 py-8 text-center"><Package size={23} className="mx-auto text-slate-400" /><p className="mt-2 text-sm font-semibold">{movements.length ? 'No hay movimientos que coincidan con estos filtros.' : 'Aún no hay movimientos de inventario.'}</p></div>}
    </section>}

    {selected && <div className="fixed inset-0 z-50 flex justify-end bg-slate-900/40" role="dialog" aria-modal="true" aria-label={`Detalle de ${selected.name}`}><button type="button" aria-label="Cerrar detalle" className="absolute inset-0 cursor-default" onClick={() => setSelectedId(null)} /><aside className="relative z-10 flex h-full w-full max-w-md flex-col bg-white shadow-xl"><header className="flex items-start justify-between border-b border-slate-200 p-4"><div><p className="text-[11px] font-bold uppercase tracking-wide text-teal-700">Detalle del insumo</p><h2 className="mt-1 text-xl font-extrabold">{selected.name}</h2><p className="mt-1 text-sm text-slate-500">{categoryName(selected)}</p></div><button type="button" aria-label="Cerrar" onClick={() => setSelectedId(null)} className="rounded-full p-2 hover:bg-slate-100"><X size={18} /></button></header><div className="min-h-0 flex-1 space-y-5 overflow-y-auto p-4"><StatusBadge state={stockState(selected)} /><div className="grid grid-cols-2 gap-3"><Detail label="Stock actual" value={stockText(selected)} /><Detail label="Stock mínimo" value={`${number(selected.minimumStockBase || 0)} ${unitName(selected.baseUnit, selected.stockUnitLabel)}`} /><Detail label="Unidad base" value={unitName(selected.baseUnit, selected.stockUnitLabel)} /><Detail label="Costo por unidad" value={selected.unitCost === undefined ? 'Sin registrar' : money(selected.unitCost)} /><Detail label="Valor actual" value={selected.unitCost === undefined ? 'Sin costo registrado' : money((selected.stockBase || 0) * selected.unitCost)} /></div><div><h3 className="text-sm font-bold">Movimientos recientes</h3><div className="mt-2 divide-y divide-slate-100">{movements.filter(item => item.productId === selected.id).sort((a, b) => b.createdAt.localeCompare(a.createdAt)).slice(0, 5).map(item => <div key={item.id} className="py-2"><div className="flex items-center justify-between gap-2"><MovementBadge type={item.type} /><strong className="text-sm tabular-nums">{item.quantityBase > 0 ? '+' : ''}{number(item.quantityBase)} {unitName(selected.baseUnit, selected.stockUnitLabel)}</strong></div><p className="mt-1 text-xs text-slate-500">{new Date(item.createdAt).toLocaleString('es-BO', { dateStyle: 'short', timeStyle: 'short' })} · {item.createdBy || 'Legado'} · {item.reason || 'Sin motivo'}</p></div>)}{!movements.some(item => item.productId === selected.id) && <p className="py-4 text-sm text-slate-500">Sin movimientos registrados.</p>}</div></div></div><footer className="flex gap-2 border-t border-slate-200 p-4"><button type="button" onClick={() => { setSelectedId(null); openMovement(selected) }} className="flex-1 rounded-xl bg-teal-500 px-3 py-3 text-sm font-bold text-slate-950">+ Movimiento</button><button type="button" onClick={() => { setSelectedId(null); openProduct(selected) }} className="flex-1 rounded-xl border border-slate-300 px-3 py-3 text-sm font-bold">Editar</button></footer></aside></div>}

    <Modal isOpen={!!editing} onClose={() => setEditing(null)} title={form.id ? 'Editar insumo' : 'Nuevo insumo'} size="lg" footer={<button type="button" onClick={saveProduct} className="w-full rounded-xl bg-slate-900 p-3 text-sm font-bold text-white transition hover:bg-slate-800">Guardar insumo</button>}>
      <div className="space-y-4"><section><h3 className="mb-3 text-xs font-extrabold uppercase tracking-wide text-slate-700">Información</h3><div className="grid gap-3 sm:grid-cols-2"><Field label="Nombre" required error={formErrors.name}><TextInput value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} /></Field><Field label="Categoría"><SelectInput value={newCategory || !['General', ...categories].includes(form.description || 'General') ? '__new' : form.description || 'General'} onChange={event => { if (event.target.value === '__new') { setNewCategory(true); setForm({ ...form, description: '' }) } else { setNewCategory(false); setForm({ ...form, description: event.target.value }) } }}><option value="General">General</option>{categories.filter(name => name !== 'General').map(name => <option key={name} value={name}>{name}</option>)}<option value="__new">+ Nueva categoría</option></SelectInput></Field>{(newCategory || !['General', ...categories].includes(form.description || 'General')) && <Field label="Nueva categoría" hint="Se guardará como categoría de este insumo."><TextInput value={form.description || ''} onChange={event => setForm({ ...form, description: event.target.value })} placeholder="Ej. Lácteos" /></Field>}<Field label="Unidad base"><SelectInput value={form.baseUnit || 'unit'} onChange={event => setForm({ ...form, baseUnit: event.target.value as Product['baseUnit'] })}><option value="unit">Unidad</option><option value="g">Gramo (g)</option><option value="ml">Mililitro (ml)</option></SelectInput></Field>{form.baseUnit === 'unit' && <Field label="Nombre de unidad" hint="Opcional: botella, lata o unidad."><TextInput value={form.stockUnitLabel || ''} onChange={event => setForm({ ...form, stockUnitLabel: event.target.value })} placeholder="Ej. botella" /></Field>}</div></section>
      <section className="border-t border-slate-200 pt-4"><h3 className="mb-3 text-xs font-extrabold uppercase tracking-wide text-slate-700">Inventario y costo</h3><div className="grid gap-3 sm:grid-cols-2"><Field label="Stock actual" error={formErrors.stock}><div className="flex items-center gap-2"><NumberInput min="0" step="0.001" value={form.stockBase ?? ''} onChange={event => setForm({ ...form, stockBase: event.target.value === '' ? NaN : Number(event.target.value) })} /><span className="shrink-0 text-xs font-bold text-slate-500">{unitName(form.baseUnit, form.stockUnitLabel)}</span></div></Field><Field label="Stock mínimo" error={formErrors.minimum} hint="Te avisaremos cuando el stock llegue a este nivel."><div className="flex items-center gap-2"><NumberInput min="0" step="0.001" value={form.minimumStockBase ?? ''} onChange={event => setForm({ ...form, minimumStockBase: event.target.value === '' ? NaN : Number(event.target.value) })} /><span className="shrink-0 text-xs font-bold text-slate-500">{unitName(form.baseUnit, form.stockUnitLabel)}</span></div></Field><Field label="Costo por unidad base" error={formErrors.cost}><div className="flex items-center gap-2"><span className="text-sm font-bold text-slate-600">Bs</span><NumberInput min="0" step="0.01" value={form.unitCost ?? ''} onChange={event => setForm({ ...form, unitCost: event.target.value === '' ? undefined : Number(event.target.value) })} /></div></Field><label className="flex items-center justify-between gap-3 rounded-xl border border-slate-200 px-3 py-2"><span><strong className="block text-sm">{form.isActive ? 'Activo' : 'Inactivo'}</strong><span className="text-xs text-slate-500">Disponible para operar</span></span><span className="relative shrink-0"><input type="checkbox" role="switch" checked={form.isActive} onChange={event => setForm({ ...form, isActive: event.target.checked })} className="peer sr-only" /><span className="block h-6 w-11 rounded-full bg-slate-300 transition-colors peer-checked:bg-teal-600 peer-focus-visible:outline peer-focus-visible:outline-2 peer-focus-visible:outline-offset-2 peer-focus-visible:outline-teal-600" /><span className="pointer-events-none absolute left-0.5 top-0.5 h-5 w-5 rounded-full bg-white shadow-sm transition-transform peer-checked:translate-x-5" /></span></label></div>{Number.isFinite(form.stockBase) && Number.isFinite(form.unitCost) && <p className="mt-3 rounded-xl bg-slate-50 px-3 py-2 text-xs text-slate-600">Valor del stock {form.id ? 'actual' : 'inicial'} <strong className="ml-1 text-sm tabular-nums text-slate-900">{money((form.stockBase || 0) * (form.unitCost || 0))}</strong></p>}</section></div>
    </Modal>
    <Modal isOpen={!!removing} onClose={() => setRemoving(null)} title="Desactivar insumo" footer={<div className="flex gap-2"><button type="button" onClick={() => setRemoving(null)} className="flex-1 rounded-xl border p-3 font-bold">Cancelar</button><button type="button" onClick={() => { if (removing) onSaveProducts(products.map(item => item.id === removing.id ? { ...item, isActive: false, isVisible: false } : item)); setRemoving(null); setNotice('Insumo desactivado. Se conservaron el stock y los movimientos.') }} className="flex-1 rounded-xl bg-rose-700 p-3 font-bold text-white">Desactivar</button></div>}><p className="text-sm">Se conservarán el stock y todos los movimientos históricos. El insumo dejará de ofrecerse para nuevos pedidos.</p></Modal>
    <Modal isOpen={!!movementProduct} onClose={() => setMovementProduct(null)} title={`Movimiento · ${movementProduct?.name || ''}`} footer={<button type="button" onClick={saveMovement} className="w-full rounded-xl bg-slate-900 p-3 font-bold text-white">Registrar movimiento</button>}><div className="grid gap-3"><p className="rounded-xl bg-slate-50 p-3 text-sm text-slate-600">Stock actual: <strong className="tabular-nums text-slate-900">{movementProduct ? stockText(movementProduct) : '—'}</strong></p><Field label="Tipo"><SelectInput value={movementType} onChange={event => setMovementType(event.target.value as ManualType)}>{(['purchase', 'waste', 'loss', 'courtesy', 'internal_consumption', 'manual_adjustment'] as const).map(type => <option key={type} value={type}>{movementNames[type]}</option>)}</SelectInput></Field><div className="grid grid-cols-2 gap-2"><Field label={movementType === 'manual_adjustment' ? 'Nuevo stock' : 'Cantidad'}><NumberInput min="0" step="0.001" value={movementAmount} onChange={event => setMovementAmount(event.target.value)} /></Field><Field label="Unidad"><SelectInput value={movementUnit} onChange={event => setMovementUnit(event.target.value as typeof movementUnit)}><option value={movementProduct?.baseUnit || 'unit'}>{unitName(movementProduct?.baseUnit, movementProduct?.stockUnitLabel)}</option>{movementProduct?.baseUnit === 'g' && <option value="kg">Kilogramo (kg)</option>}{movementProduct?.baseUnit === 'ml' && <option value="l">Litro (L)</option>}</SelectInput></Field></div><Field label="Motivo"><TextInput value={reason} onChange={event => setReason(event.target.value)} /></Field>{movementError && <p role="alert" className="text-sm font-semibold text-rose-700">{movementError}</p>}</div></Modal>
  </div>
}

function SummaryCard({ label, value, icon: Icon, active, onClick, tone = 'teal' }: { label: string; value: string; icon: typeof Boxes; active: boolean; onClick: () => void; tone?: 'teal' | 'amber' | 'rose' }) { return <button type="button" onClick={onClick} aria-pressed={active} className={`rounded-2xl border p-4 text-left transition hover:border-teal-300 focus-visible:outline focus-visible:outline-2 focus-visible:outline-teal-600 ${active ? 'border-teal-300 bg-teal-50/50' : 'border-slate-200 bg-white'}`}><div className="flex items-center justify-between gap-2"><span className="text-[11px] font-bold uppercase tracking-wide text-slate-600">{label}</span><Icon size={18} className={tone === 'amber' ? 'text-amber-600' : tone === 'rose' ? 'text-rose-600' : 'text-teal-700'} /></div><strong className="mt-2 block text-2xl font-extrabold tabular-nums">{value}</strong><span className="mt-1 block text-[11px] text-slate-500">Ver insumos</span></button> }
function EmptyInventory({ filtered }: { filtered: boolean }) { return <div className="rounded-2xl border border-dashed border-slate-200 bg-white px-4 py-8 text-center"><Package size={23} className="mx-auto text-slate-400" /><p className="mt-2 text-sm font-semibold">{filtered ? 'No hay insumos que coincidan con estos filtros.' : 'Aún no hay insumos registrados.'}</p><p className="mt-1 text-xs text-slate-500">{filtered ? 'Prueba otra búsqueda o estado.' : 'Crea el primer insumo para empezar a controlar el stock.'}</p></div> }
function Detail({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-slate-200 p-3"><span className="block text-[11px] font-bold uppercase tracking-wide text-slate-500">{label}</span><strong className="mt-1 block break-words text-sm tabular-nums">{value}</strong></div> }
function MovementCard({ item, product }: { item: InventoryMovement; product?: Product }) { return <div className="rounded-2xl border border-slate-200 bg-white p-3"><div className="flex flex-wrap items-start justify-between gap-2"><div><strong className="block text-sm">{item.productName || product?.name || item.productId}</strong><span className="mt-1 block text-xs text-slate-500">{new Date(item.createdAt).toLocaleString('es-BO', { dateStyle: 'short', timeStyle: 'short' })}</span></div><strong className={`text-sm tabular-nums ${item.quantityBase < 0 ? 'text-rose-700' : 'text-emerald-700'}`}>{item.quantityBase > 0 ? '+' : item.quantityBase < 0 ? '−' : ''}{number(Math.abs(item.quantityBase))} {unitName(product?.baseUnit, product?.stockUnitLabel)}</strong></div><div className="mt-2"><MovementBadge type={item.type} /></div><p className="mt-2 text-xs text-slate-600">{item.tableId ? `Mesa ${item.tableId} · ` : ''}{item.orderId ? `Pedido ${item.orderId} · ` : ''}{item.reason || 'Manual'}</p><p className="mt-1 text-xs text-slate-500">{item.createdBy || 'Legado'}{item.previousStock === undefined ? '' : ` · Stock ${number(item.previousStock)} → ${number(item.newStock ?? 0)}`}</p></div> }
