import { useMemo, useState } from 'react'
import { MessageCircle, MoreHorizontal, Plus, Search, X } from 'lucide-react'
import type { Order } from '../../types'
import { customerName, customerSummary, phoneDigits, whatsappUrl, type RestaurantCustomer } from '../../modules/restaurant/domain/restaurantCustomers'
import { RestaurantCustomerForm, type CustomerDraft } from './RestaurantCustomerForm'

const date = (value?: string) => value ? new Date(value).toLocaleDateString('es-BO') : '—'
const money = (value: number) => `Bs ${value.toLocaleString('es-BO', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`

export function RestaurantCustomers({ orders, customers, restaurantName, canManage, onSaveCustomer, onArchiveCustomer }: {
  orders: Order[]; customers: RestaurantCustomer[]; restaurantName: string; canManage: boolean
  onSaveCustomer?: (draft: CustomerDraft, id?: string) => RestaurantCustomer | null
  onArchiveCustomer?: (id: string) => void
}) {
  const [query, setQuery] = useState('')
  const [editing, setEditing] = useState<RestaurantCustomer | 'new' | null>(null)
  const [viewing, setViewing] = useState<RestaurantCustomer | null>(null)
  const [menu, setMenu] = useState<string | null>(null)
  const [whatsappMenu, setWhatsappMenu] = useState<string | null>(null)
  const [archiving, setArchiving] = useState<RestaurantCustomer | null>(null)
  const rows = useMemo(() => customers.filter(customer => {
    const text = `${customerName(customer)} ${customer.normalizedPhone} ${customer.email || ''}`.toLocaleLowerCase('es-BO')
    return text.includes(query.toLocaleLowerCase('es-BO')) || (!!phoneDigits(query) && phoneDigits(customer.phone).includes(phoneDigits(query)))
  }).sort((a, b) => Number(b.active) - Number(a.active) || customerName(a).localeCompare(customerName(b), 'es-BO')), [customers, query])
  const openWhatsapp = (customer: RestaurantCustomer, message?: string) => {
    const url = whatsappUrl(customer, message)
    if (url) window.open(url, '_blank', 'noopener,noreferrer')
    setWhatsappMenu(null)
  }
  const whatsappActions = (customer: RestaurantCustomer) => <div className="relative flex items-center gap-1"><button type="button" disabled={!customer.normalizedPhone} onClick={() => openWhatsapp(customer)} className="inline-flex min-h-9 items-center gap-1.5 rounded-lg border border-emerald-200 bg-emerald-50 px-3 text-xs font-bold text-emerald-800 disabled:opacity-40"><MessageCircle size={15} /> WhatsApp</button><button type="button" aria-label={`Opciones WhatsApp de ${customerName(customer)}`} disabled={!customer.normalizedPhone} onClick={() => setWhatsappMenu(whatsappMenu === customer.id ? null : customer.id)} className="min-h-9 rounded-lg border border-emerald-200 px-2 text-xs text-emerald-800">▾</button>{whatsappMenu === customer.id && <div className="absolute right-0 top-10 z-20 w-44 rounded-xl border border-slate-200 bg-white p-1 shadow-lg"><button type="button" onClick={() => openWhatsapp(customer)} className="block w-full rounded-lg p-2 text-left text-xs hover:bg-slate-50">Abrir conversación</button><button type="button" onClick={() => openWhatsapp(customer, `Hola ${customer.firstName}, somos de ${restaurantName}.`)} className="block w-full rounded-lg p-2 text-left text-xs hover:bg-slate-50">Enviar saludo</button><button type="button" onClick={() => openWhatsapp(customer, `Hola ${customer.firstName}, queremos confirmar tu reserva.`)} className="block w-full rounded-lg p-2 text-left text-xs hover:bg-slate-50">Confirmar reserva</button></div>}</div>
  const actions = (customer: RestaurantCustomer) => <div className="relative"><button type="button" aria-label={`Acciones de ${customerName(customer)}`} onClick={() => setMenu(menu === customer.id ? null : customer.id)} className="rounded-lg p-2 text-slate-600 hover:bg-slate-100"><MoreHorizontal size={18} /></button>{menu === customer.id && <div className="absolute right-0 top-10 z-20 w-36 rounded-xl border border-slate-200 bg-white p-1 shadow-lg"><button type="button" onClick={() => { setViewing(customer); setMenu(null) }} className="block w-full rounded-lg p-2 text-left text-xs hover:bg-slate-50">Ver cliente</button>{canManage && onSaveCustomer && <button type="button" onClick={() => { setEditing(customer); setMenu(null) }} className="block w-full rounded-lg p-2 text-left text-xs hover:bg-slate-50">Editar</button>}{customer.normalizedPhone && <button type="button" onClick={() => openWhatsapp(customer)} className="block w-full rounded-lg p-2 text-left text-xs hover:bg-slate-50">WhatsApp</button>}{canManage && onArchiveCustomer && customer.active && <button type="button" onClick={() => { setArchiving(customer); setMenu(null) }} className="block w-full rounded-lg p-2 text-left text-xs text-rose-700 hover:bg-rose-50">Desactivar</button>}</div>}</div>
  const rowActions = (customer: RestaurantCustomer) => <div className="flex justify-end gap-2">{whatsappActions(customer)}{actions(customer)}</div>
  return <div className="space-y-5"><header className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-bold text-slate-900">Clientes</h1><p className="text-sm text-slate-500">Contactos e historial de consumo del restaurante.</p></div>{onSaveCustomer && <button type="button" onClick={() => setEditing('new')} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-slate-900 px-4 text-sm font-bold text-white"><Plus size={16} /> Nuevo cliente</button>}</header>
    <div className="relative"><Search size={16} className="absolute left-3 top-3 text-slate-400" /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Buscar cliente, teléfono o email..." className="w-full rounded-xl border border-slate-200 bg-white py-2.5 pl-9 pr-3 text-sm" /></div>
    <div className="hidden rounded-2xl border border-slate-200 bg-white md:block"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-4">Cliente</th><th className="p-4">Teléfono</th><th className="p-4 text-center">Visitas</th><th className="p-4">Última visita</th><th className="p-4 text-right">Acciones</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(customer => { const summary = customerSummary(customer, orders); return <tr key={customer.id}><td className="p-4"><button type="button" onClick={() => setViewing(customer)} className="font-semibold text-slate-900 hover:underline">{customerName(customer)}</button>{!customer.active && <span className="ml-2 rounded-full bg-slate-100 px-2 py-0.5 text-[10px] text-slate-500">Archivado</span>}</td><td className="p-4 text-slate-600">{customer.normalizedPhone ? `+${customer.countryCode} ${customer.phone}` : '—'}</td><td className="p-4 text-center">{summary.visits}</td><td className="p-4">{date(summary.lastVisit)}</td><td className="p-4">{rowActions(customer)}</td></tr> })}</tbody></table></div>
    <div className="space-y-2 md:hidden">{rows.map(customer => { const summary = customerSummary(customer, orders); return <div key={customer.id} className="rounded-2xl border border-slate-200 bg-white p-4"><button type="button" onClick={() => setViewing(customer)} className="font-bold text-slate-900">{customerName(customer)}</button>{!customer.active && <span className="ml-2 text-xs text-slate-500">Archivado</span>}<p className="mt-1 text-xs text-slate-600">{customer.normalizedPhone ? `+${customer.countryCode} ${customer.phone}` : 'Sin teléfono'}</p><p className="mt-2 text-xs text-slate-500">{summary.visits} visitas · Última: {date(summary.lastVisit)}</p><div className="mt-3">{rowActions(customer)}</div></div> })}</div>
    {!rows.length && <p className="rounded-2xl border border-dashed border-slate-200 p-8 text-center text-sm text-slate-500">{query ? 'No encontramos clientes con esa búsqueda.' : 'Aún no hay clientes. Crea el primero con nombre y teléfono.'}</p>}
    {editing && onSaveCustomer && <RestaurantCustomerForm key={editing === 'new' ? 'new' : editing.id} customer={editing === 'new' ? undefined : editing} customers={customers} onClose={() => setEditing(null)} onSave={(draft, id) => { const saved = onSaveCustomer(draft, id); if (saved) { setEditing(null); setViewing(saved) } }} onDuplicate={existing => { setEditing(null); setViewing(existing) }} />}
    {viewing && <div className="fixed inset-0 z-[100] flex justify-end bg-slate-950/50" onClick={() => setViewing(null)}><aside role="dialog" aria-modal="true" aria-label={`Cliente ${customerName(viewing)}`} onClick={event => event.stopPropagation()} className="h-full w-full max-w-lg overflow-y-auto bg-white p-5 shadow-2xl"><header className="flex items-start justify-between"><div><h2 className="text-xl font-bold">{customerName(viewing)}</h2><p className="text-xs text-slate-500">{viewing.active ? 'Cliente activo' : 'Cliente archivado'}</p></div><button type="button" aria-label="Cerrar" onClick={() => setViewing(null)}><X size={18} /></button></header><div className="mt-4 flex gap-2">{whatsappActions(viewing)}{canManage && onSaveCustomer && <button type="button" onClick={() => { setEditing(viewing); setViewing(null) }} className="rounded-lg border border-slate-200 px-3 text-xs font-bold">Editar</button>}</div><section className="mt-6 space-y-2 rounded-xl bg-slate-50 p-4 text-sm"><h3 className="font-bold">Información</h3><p>Teléfono: {viewing.normalizedPhone ? `+${viewing.countryCode} ${viewing.phone}` : '—'}</p><p>Email: {viewing.email || '—'}</p><p>Cumpleaños: {viewing.birthday || '—'}</p><p>Notas: {viewing.notes || '—'}</p></section>{canManage && (() => { const summary = customerSummary(viewing, orders); return <section className="mt-5"><h3 className="font-bold">Historial</h3><p className="mt-2 text-sm text-slate-600">{summary.visits} visitas · Última: {date(summary.lastVisit)} · Consumido: {money(summary.totalSpent)}</p><div className="mt-3 divide-y divide-slate-100">{summary.orders.slice(0, 10).map(order => <div key={order.id} className="flex justify-between py-3 text-sm"><div><p className="font-semibold">{date(order.paidAt || order.createdAt)}</p><p className="text-xs text-slate-500">{order.tableInfo || 'Para llevar'} · #{order.displayNumber}</p></div><span className="font-bold">{money(order.total)}</span></div>)}{!summary.orders.length && <p className="py-4 text-sm text-slate-500">Sin pedidos asociados.</p>}</div></section> })()}</aside></div>}
    {archiving && <div className="fixed inset-0 z-[120] grid place-items-center bg-slate-950/50 p-4"><section role="dialog" aria-modal="true" aria-label="Desactivar cliente" className="w-full max-w-sm rounded-2xl bg-white p-5"><h3 className="font-bold">Desactivar cliente</h3><p className="mt-2 text-sm text-slate-600">Se conservarán sus pedidos y su historial.</p><div className="mt-4 flex gap-2"><button type="button" onClick={() => setArchiving(null)} className="flex-1 rounded-xl border p-3 text-sm font-semibold">Cancelar</button><button type="button" onClick={() => { onArchiveCustomer?.(archiving.id); setArchiving(null) }} className="flex-1 rounded-xl bg-rose-700 p-3 text-sm font-bold text-white">Desactivar</button></div></section></div>}
  </div>
}
