import { useState } from 'react'
import { NumberInput } from '../../components/ui/Form'
import type { InventoryShiftRow } from '../../modules/restaurant/domain/inventoryEngine'

const fmt = (value: number) => value.toLocaleString('es-BO', { maximumFractionDigits: 3 })

export function RestaurantShiftInventory({ rows, onCount }: { rows: InventoryShiftRow[]; onCount?: (productId: string, physical: number, note?: string) => void }) {
  const [notes, setNotes] = useState<Record<string, string>>({})
  const pending = rows.filter(row => row.physical === undefined).length
  const shortages = rows.filter(row => (row.difference || 0) < 0).length
  const surpluses = rows.filter(row => (row.difference || 0) > 0).length
  const differenceValue = rows.reduce((total, row) => total + Math.abs(row.difference || 0) * row.unitCost, 0)
  const soldProducts = rows.filter(row => row.sales < 0).length
  return <section className="mt-5 rounded-xl border border-slate-200 bg-white p-3">
    <div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div><h3 className="text-sm font-bold text-slate-900">Arqueo físico de inventario</h3><p className="text-xs text-slate-500">Stock inicial + entradas − ventas − mermas ± ajustes. El conteo no modifica stock automáticamente.</p></div><span className={`rounded-full px-2 py-1 text-xs font-bold ${pending ? 'bg-amber-50 text-amber-800' : 'bg-emerald-50 text-emerald-800'}`}>{pending ? `${pending} pendientes` : 'Completo'}</span></div>
    <div className="mb-3 grid grid-cols-2 gap-2 text-xs sm:grid-cols-4"><p className="rounded-lg bg-slate-50 p-2">Insumos vendidos <strong className="block">{soldProducts}</strong></p><p className="rounded-lg bg-slate-50 p-2">Con diferencia <strong className="block">{shortages + surpluses}</strong></p><p className="rounded-lg bg-rose-50 p-2">Faltantes <strong className="block">{shortages}</strong></p><p className="rounded-lg bg-sky-50 p-2">Sobrantes <strong className="block">{surpluses} · Bs {fmt(differenceValue)}</strong></p></div>
    <div className="max-h-72 overflow-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="sticky top-0 bg-slate-50 text-slate-600"><tr><th className="p-2">Insumo</th><th className="p-2 text-right">Inicial</th><th className="p-2 text-right">Entradas</th><th className="p-2 text-right">Ventas</th><th className="p-2 text-right">Devol.</th><th className="p-2 text-right">Mermas</th><th className="p-2 text-right">Ajustes</th><th className="p-2 text-right">Teórico</th><th className="p-2">Físico</th><th className="p-2 text-right">Dif.</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(row => <tr key={row.productId}><td className="p-2 font-semibold">{row.name} <small className="text-slate-500">{row.unit}</small>{row.difference !== undefined && row.difference !== 0 && <input aria-label={`Observación de ${row.name}`} value={notes[row.productId] ?? row.count?.note ?? ''} onChange={event => setNotes(previous => ({ ...previous, [row.productId]: event.target.value }))} onBlur={event => onCount?.(row.productId, row.physical!, event.target.value)} placeholder="Observación opcional" className="mt-1 block w-full rounded border border-slate-200 px-2 py-1 text-[11px] font-normal" />}</td><td className="p-2 text-right">{fmt(row.initial)}</td><td className="p-2 text-right">{fmt(row.incoming)}</td><td className="p-2 text-right">{fmt(row.sales)}</td><td className="p-2 text-right">+{fmt(row.returns)}</td><td className="p-2 text-right">{fmt(row.waste)}</td><td className="p-2 text-right">{fmt(row.adjustments)}</td><td className="p-2 text-right font-bold">{fmt(row.theoretical)}</td><td className="w-24 p-2"><NumberInput aria-label={`Conteo físico de ${row.name}`} min="0" step="0.001" value={row.physical ?? ''} onChange={event => { if (event.target.value !== '') onCount?.(row.productId, Number(event.target.value), notes[row.productId] ?? row.count?.note) }} /></td><td className={`p-2 text-right font-bold ${row.difference && row.difference !== 0 ? 'text-amber-700' : 'text-slate-600'}`}>{row.difference === undefined ? '—' : fmt(row.difference)}</td></tr>)}{!rows.length && <tr><td colSpan={10} className="p-4 text-center text-slate-500">Sin insumos en este turno.</td></tr>}</tbody></table></div>
  </section>
}
