import type { Product } from '../../types'
import { Field, NumberInput, SelectInput, TextInput } from '../../components/ui/Form'

export function RestaurantProductInventoryFields({ form, products, onChange }: { form: Product; products: Product[]; onChange: (next: Product) => void }) {
  const inventoryItems = products.filter(item => item.id !== form.id && item.stockBase !== undefined && item.isActive)
  const recipe = form.recipe || []
  const setRecipe = (next: Product['recipe']) => onChange({ ...form, recipe: next, stockBase: next?.length ? undefined : form.stockBase })
  return <section className="rounded-xl border border-slate-200 bg-slate-50 p-3"><h3 className="mb-2 text-sm font-bold text-slate-900">Inventario</h3>
    <p className="mb-3 text-xs text-slate-500">Venta directa: descuenta una unidad por producto. Receta: descuenta los insumos indicados al confirmar el pedido.</p>
    {!recipe.length && <div className="grid gap-3 sm:grid-cols-2"><Field label="Stock actual (opcional)"><NumberInput min="0" step="0.001" value={form.stockBase ?? ''} onChange={event => onChange({ ...form, stockBase: event.target.value === '' ? undefined : Number(event.target.value) })} /></Field><Field label="Stock mínimo"><NumberInput min="0" step="0.001" value={form.minimumStockBase ?? ''} onChange={event => onChange({ ...form, minimumStockBase: event.target.value === '' ? undefined : Number(event.target.value) })} /></Field></div>}
    {!recipe.length && form.stockBase !== undefined && <Field label="Costo por unidad base (opcional)"><NumberInput min="0" step="0.01" value={form.unitCost ?? ''} onChange={event => onChange({ ...form, unitCost: event.target.value === '' ? undefined : Number(event.target.value) })} /></Field>}
    {!recipe.length && form.baseUnit === 'unit' && <Field label="Nombre de unidad (opcional)"><TextInput value={form.stockUnitLabel || ''} onChange={event => onChange({ ...form, stockUnitLabel: event.target.value })} placeholder="botella, lata, unidad" /></Field>}
    {form.restaurantType !== 'ingredient' && <><div className="mt-3 space-y-2">{recipe.map((part, index) => { const ingredient = inventoryItems.find(item => item.id === part.ingredientId); return <div key={`${part.ingredientId}-${index}`} className="grid grid-cols-[1fr_90px_auto] items-end gap-2"><Field label={index ? 'Insumo' : 'Insumo de la receta'}><SelectInput value={part.ingredientId} onChange={event => setRecipe(recipe.map((item, at) => at === index ? { ...item, ingredientId: event.target.value } : item))}>{inventoryItems.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</SelectInput></Field><Field label={`Cantidad ${ingredient?.baseUnit || 'unit'}`}><NumberInput min="0.001" step="0.001" value={part.quantityBase} onChange={event => setRecipe(recipe.map((item, at) => at === index ? { ...item, quantityBase: Number(event.target.value) } : item))} /></Field><button type="button" onClick={() => setRecipe(recipe.filter((_, at) => at !== index))} className="rounded-lg border border-rose-200 px-2 py-2 text-xs font-bold text-rose-700">Quitar</button></div> })}</div>{inventoryItems.length > 0 && <button type="button" onClick={() => setRecipe([...recipe, { ingredientId: inventoryItems[0].id, quantityBase: 1 }])} className="mt-3 rounded-lg border border-teal-300 px-3 py-2 text-xs font-bold text-teal-800">+ Añadir ingrediente</button>}</>}
    <p className="mt-2 text-[11px] text-slate-500">Las cantidades de receta se guardan en la unidad base del insumo: g, ml o unidad.</p>
  </section>
}
