import type { Product } from '../../types'
import { Field, NumberInput, SelectInput, TextInput } from '../../components/ui/Form'
import { compatibleInventoryUnits, fromBaseQuantity, toBaseQuantity, unitLabel, type InventoryUnit } from '../../modules/shared/domain/inventoryUnits'

export function RestaurantProductInventoryFields({ form, products, onChange }: { form: Product; products: Product[]; onChange: (next: Product) => void }) {
  const inventoryItems = products.filter(item => item.id !== form.id && item.stockBase !== undefined && item.isActive)
  const recipe = form.recipe || []
  const setRecipe = (next: Product['recipe']) => onChange({ ...form, recipe: next, stockBase: next?.length ? undefined : form.stockBase })
  return <section className="rounded-xl border border-slate-200 bg-slate-50 p-3"><h3 className="mb-2 text-sm font-bold text-slate-900">Inventario</h3>
    <p className="mb-3 text-xs text-slate-500">La receta se guarda en la unidad base, pero puedes medir peso en g/kg y volumen en ml/L.</p>
    {!recipe.length && <div className="grid gap-3 sm:grid-cols-2"><Field label={`Stock actual (${unitLabel(form.displayUnit || form.baseUnit)})`}><NumberInput min="0" step="0.001" value={fromBaseQuantity(form.stockBase ?? 0, form.displayUnit || form.baseUnit)} onChange={event => onChange({ ...form, stockBase: event.target.value === '' ? undefined : toBaseQuantity(Number(event.target.value), (form.displayUnit || form.baseUnit || 'unit') as InventoryUnit) })} /></Field><Field label={`Stock mínimo (${unitLabel(form.displayUnit || form.baseUnit)})`}><NumberInput min="0" step="0.001" value={fromBaseQuantity(form.minimumStockBase ?? 0, form.displayUnit || form.baseUnit)} onChange={event => onChange({ ...form, minimumStockBase: event.target.value === '' ? undefined : toBaseQuantity(Number(event.target.value), (form.displayUnit || form.baseUnit || 'unit') as InventoryUnit) })} /></Field></div>}
    {!recipe.length && form.stockBase !== undefined && <Field label="Costo por unidad base (opcional)"><NumberInput min="0" step="0.01" value={form.unitCost ?? ''} onChange={event => onChange({ ...form, unitCost: event.target.value === '' ? undefined : Number(event.target.value) })} /></Field>}
    {!recipe.length && form.baseUnit === 'unit' && <Field label="Nombre de unidad (opcional)"><TextInput value={form.stockUnitLabel || ''} onChange={event => onChange({ ...form, stockUnitLabel: event.target.value })} placeholder="botella, lata, unidad" /></Field>}
    {form.restaurantType !== 'ingredient' && <><div className="mt-3 space-y-2">{recipe.map((part, index) => { const ingredient = inventoryItems.find(item => item.id === part.ingredientId); const displayUnit = (part.displayUnit || ingredient?.displayUnit || ingredient?.baseUnit || 'unit') as InventoryUnit; const units = compatibleInventoryUnits(ingredient?.baseUnit); return <div key={`${part.ingredientId}-${index}`} className="grid grid-cols-[1fr_85px_75px_auto] items-end gap-2"><Field label={index ? 'Insumo' : 'Insumo de la receta'}><SelectInput value={part.ingredientId} onChange={event => { const next = inventoryItems.find(item => item.id === event.target.value); setRecipe(recipe.map((item, at) => at === index ? { ...item, ingredientId: event.target.value, quantityBase: 1, displayUnit: next?.displayUnit || next?.baseUnit } : item)) }}>{inventoryItems.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</SelectInput></Field><Field label="Cantidad"><NumberInput min="0.001" step="0.001" value={fromBaseQuantity(part.quantityBase, displayUnit)} onChange={event => setRecipe(recipe.map((item, at) => at === index ? { ...item, quantityBase: toBaseQuantity(Number(event.target.value), displayUnit) } : item))} /></Field><Field label="Unidad"><SelectInput value={displayUnit} onChange={event => { const unit = event.target.value as InventoryUnit; setRecipe(recipe.map((item, at) => at === index ? { ...item, displayUnit: unit } : item)) }}>{units.map(unit => <option key={unit} value={unit}>{unitLabel(unit)}</option>)}</SelectInput></Field><button type="button" onClick={() => setRecipe(recipe.filter((_, at) => at !== index))} className="rounded-lg border border-rose-200 px-2 py-2 text-xs font-bold text-rose-700">Quitar</button></div> })}</div>{inventoryItems.length > 0 && <button type="button" onClick={() => { const first = inventoryItems[0]; setRecipe([...recipe, { ingredientId: first.id, quantityBase: 1, displayUnit: first.displayUnit || first.baseUnit }]) }} className="mt-3 rounded-lg border border-teal-300 px-3 py-2 text-xs font-bold text-teal-800">+ Añadir ingrediente</button>}</>}
  </section>
}