import { useMemo, useState } from 'react'
import type { ReactNode } from 'react'
import { BarChart3, Boxes, CircleDollarSign, ClipboardList, GlassWater, LayoutGrid, LogOut, Menu, Music2, ReceiptText, Sparkles, Users, Wine } from 'lucide-react'
import type { NightclubModuleId, NightclubRoundDraft, NightclubServiceTarget } from '../domain/nightclubAccounts'
import { nightclubAccountLabel, nightclubCan, nightclubCashSummary, nightclubPaidTotal, normalizeNightclubRole } from '../domain/nightclubAccounts'
import type { useNightclubController } from './useNightclubController'
import { NightclubCash } from './NightclubCash'
import { NightclubInventory } from './NightclubInventory'
import { NightclubProducts } from './NightclubProducts'
import { NightclubCustomers } from './NightclubCustomers'
import { NightclubFloor } from './NightclubFloor'
import { NightclubPOS } from './NightclubPOS'
import { NightclubZones } from './NightclubZones'
import { NightclubAccounts } from './NightclubAccounts'
import { NightclubBar } from './NightclubBar'
import { NightclubReports } from './NightclubReports'
import { NightclubCourtesyDialog, NightclubCourtesyReport, NightclubMembers } from './NightclubMembers'
import { NightclubCourtesyInventoryMovements, NightclubInventoryCosts } from './NightclubInventoryCosts'

type NightclubModule = NightclubModuleId
type Props = ReturnType<typeof useNightclubController> & { companyName: string; logoUrl?: string; userName: string; role: string; onSignOut?: () => void | Promise<void> }
const allModules: Array<{ id: NightclubModule; label: string; icon: typeof Music2 }> = [
  { id: 'dashboard', label: 'Inicio', icon: BarChart3 }, { id: 'floor', label: 'Zonas', icon: LayoutGrid },
  { id: 'pos', label: 'POS', icon: CircleDollarSign }, { id: 'accounts', label: 'Cuentas', icon: ReceiptText },
  { id: 'bar', label: 'Barra', icon: GlassWater }, { id: 'inventory', label: 'Inventario', icon: Boxes },
  { id: 'products', label: 'Productos', icon: Wine }, { id: 'cash', label: 'Caja', icon: ClipboardList },
  { id: 'history', label: 'Historial', icon: ReceiptText }, { id: 'customers', label: 'Clientes', icon: Users }, { id: 'members', label: 'Socios', icon: Users },
  { id: 'users', label: 'Usuarios', icon: Users }, { id: 'reports', label: 'Reportes', icon: BarChart3 },
  { id: 'settings', label: 'Configuración', icon: Sparkles },
]
const money = (value: number) => `Bs ${value.toLocaleString('es-BO', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
const roleLabels = { owner: 'Propietario', admin: 'Administración', cashier: 'Caja', waiter: 'Mesero', service: 'Mesero', bar: 'Barra', inventory: 'Inventario' } as const

export function NightclubExperience({ companyName, logoUrl, userName, role, data, onSaveZone, onSaveTable, onOpenAccount, onSettleRound, onAdvanceRound, onDeliverRound, onFinishAccount, onRefundRound, onStartShift, onCloseShift, onCashMovement, onAdjustInventory, onSaveInventory, onSaveProduct, onSaveCustomer, onSaveStaff, onSaveMember, onRegisterCourtesy, onCancelCourtesy, onSignOut }: Props) {
  const normalizedRole = normalizeNightclubRole(role)
  const visibleModules = useMemo(() => allModules.filter(item => nightclubCan(normalizedRole, item.id)), [normalizedRole])
  const [activeModule, setActiveModule] = useState<NightclubModule>('dashboard')
  const [moreOpen, setMoreOpen] = useState(false)
  const [selectedAccountId, setSelectedAccountId] = useState('')
  const [draft, setDraft] = useState<NightclubRoundDraft[]>([])
  const [courtesyAccountId, setCourtesyAccountId] = useState<string | null>(null)
  const [notice, setNotice] = useState('')
  const [newStockName, setNewStockName] = useState('')
  const [newStockAmount, setNewStockAmount] = useState('')
  const [newStockUnit, setNewStockUnit] = useState<'unit' | 'ml' | 'g'>('unit')
  const [staffName, setStaffName] = useState('')
  const [staffRole, setStaffRole] = useState<'service' | 'cashier' | 'bar' | 'inventory' | 'admin'>('service')
  const activeAccounts = data.accounts.filter(account => account.status !== 'closed')
  const closedAccounts = data.accounts.filter(account => account.status === 'closed')
  const barRounds = activeAccounts.flatMap(account => account.rounds.map(batch => ({ ...batch, account, table: data.tables.find(table => table.id === account.tableId) }))).filter(batch => !!batch.authorization && (batch.status === 'pending' || batch.status === 'preparing'))
  const readyRounds = activeAccounts.flatMap(account => account.rounds.filter(batch => !!batch.authorization && batch.status === 'ready').map(batch => ({ batch, account })))
  const groupedTables = useMemo(() => data.zones.map(zone => ({ zone, tables: data.tables.filter(table => table.zoneId === zone.id) })), [data.zones, data.tables])
  const summary = nightclubCashSummary(data)
  const run = (action: () => void, message: string) => { try { action(); setNotice(message); return true } catch (error) { setNotice(error instanceof Error ? error.message : 'No se pudo completar la acción.'); return false } }
  const canDeliver = ['owner', 'admin', 'waiter', 'service'].includes(normalizedRole)
  const canRefund = ['owner', 'admin'].includes(normalizedRole)
  const mobilePriority: NightclubModule[] = normalizedRole === 'bar' ? ['bar', 'history'] : normalizedRole === 'inventory' ? ['inventory', 'products', 'history'] : normalizedRole === 'cashier' ? ['accounts', 'cash', 'pos'] : normalizedRole === 'waiter' || normalizedRole === 'service' ? ['floor', 'pos', 'accounts'] : ['dashboard', 'floor', 'reports']
  const mobileModules = mobilePriority.map(id => visibleModules.find(item => item.id === id)).filter((item): item is (typeof allModules)[number] => !!item)
  const moreModules = visibleModules.filter(item => !mobileModules.some(primary => primary.id === item.id))
  const currentModule = nightclubCan(normalizedRole, activeModule) ? activeModule : visibleModules[0]?.id || 'floor'

  return <div className="min-h-screen w-full bg-slate-950 text-slate-100"><header className="sticky top-0 z-30 flex min-h-16 items-center justify-between border-b border-amber-400/20 bg-slate-950/95 px-4 backdrop-blur md:px-6"><div className="flex items-center gap-3">{logoUrl ? <img src={logoUrl} alt="" className="h-9 w-9 rounded-xl object-cover" /> : <span className="grid h-9 w-9 place-items-center rounded-xl bg-amber-400"><Music2 size={19} /></span>}<div><strong className="block text-sm">{companyName}</strong><span className="text-[11px] text-amber-300">Club nocturno / Lounge</span></div></div><div className="flex items-center gap-3 text-right"><div><strong className="block text-xs">{userName}</strong><span className="text-[10px] uppercase text-slate-400">{roleLabels[normalizedRole]} · Turno {data.shift?.status === 'open' ? 'activo' : 'cerrado'}</span></div>{onSignOut && <button onClick={() => void onSignOut()} aria-label="Cerrar sesión" className="rounded-xl border border-slate-700 p-2"><LogOut size={16} /></button>}</div></header>
    <div className="flex w-full"><aside className="sticky top-16 hidden h-[calc(100vh-4rem)] w-60 shrink-0 overflow-y-auto border-r border-slate-800 p-3 lg:block"><nav className="space-y-1">{visibleModules.map(item => <button key={item.id} onClick={() => setActiveModule(item.id)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-semibold ${currentModule === item.id ? 'bg-amber-400 text-white' : 'text-slate-400 hover:bg-slate-900'}`}><item.icon size={17} />{item.label}</button>)}</nav></aside>
      <main className="min-w-0 flex-1 p-4 pb-24 sm:p-6 lg:pb-6">{notice && <button onClick={() => setNotice('')} role="status" className="mb-4 w-full rounded-xl border border-amber-400/30 bg-amber-400/10 p-3 text-left text-sm text-amber-100">{notice}</button>}
        {canDeliver && readyRounds.length > 0 && <button onClick={() => setActiveModule('accounts')} className="mb-4 w-full rounded-xl border border-emerald-400 bg-emerald-400/15 p-3 text-left font-bold text-emerald-200">🔔 {readyRounds.length} pedido(s) listo(s) para recoger · {readyRounds.slice(0, 3).map(({ batch, account }) => nightclubAccountLabel(account, data) + ' #' + batch.sequence).join(' · ')}</button>}
        {currentModule === 'dashboard' && <div className="space-y-6"><Title title="Operación nocturna" subtitle="Salón, rondas, inventario y caja en una sola operación." /><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Cuentas abiertas" value={String(activeAccounts.length)} /><Metric label="Mesas ocupadas" value={String(data.tables.filter(table => !!table.activeAccountId).length)} /><Metric label="Rondas en barra" value={String(barRounds.length)} /><Metric label="Ventas del turno" value={money(summary.totalSales)} /></div>{data.shift?.status !== 'open' && <button onClick={() => setActiveModule('cash')} className="rounded-xl bg-amber-400 px-5 py-3 font-bold">Iniciar turno</button>}<section className="grid gap-4 lg:grid-cols-2"><Panel title="Zonas"><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{groupedTables.map(({ zone, tables }) => <button key={zone.id} onClick={() => setActiveModule('floor')} className="rounded-xl border border-slate-800 bg-slate-900 p-3 text-left"><strong className="text-sm">{zone.name}</strong><span className="mt-1 block text-xs text-slate-400">{tables.filter(table => !!table.activeAccountId).length}/{tables.length} en uso</span></button>)}</div></Panel><Panel title="Esperando en barra"><div className="space-y-2">{barRounds.slice(0, 5).map(batch => <p key={batch.id} className="rounded-xl bg-slate-900 p-3 text-sm">{batch.table?.name} · Ronda #{batch.sequence} · {batch.status === 'pending' ? 'Pendiente' : 'Preparando'}</p>)}{!barRounds.length && <Empty text="No hay rondas pendientes." />}</div></Panel></section></div>}
        {currentModule === 'floor' && <NightclubZones data={data} onOpenAccount={id => run(() => onOpenAccount(id), 'Mesa ocupada.')} onGoToPOS={id => { setSelectedAccountId(id); setActiveModule('pos') }} onFinishAccount={id => run(() => onFinishAccount(id), 'Mesa libre.')} onDeliverRound={(id, roundId) => run(() => onDeliverRound(id, roundId), 'Pedido entregado.')} canDeliver={canDeliver} />}
        {currentModule === 'pos' && <NightclubPOS data={data} draft={draft} selectedAccountId={selectedAccountId} onSelectAccount={setSelectedAccountId} onDraftChange={setDraft} onOpenAccount={(target: NightclubServiceTarget) => { try { const id = onOpenAccount(target); setNotice('Cuenta abierta.'); return id } catch (error) { setNotice(error instanceof Error ? error.message : 'No se pudo abrir la cuenta.'); return '' } }} onSettleRound={(id, items, payment, operationId) => run(() => onSettleRound(id, items, payment, operationId), 'Ronda pagada y enviada; inventario actualizado.')} onCourtesy={setCourtesyAccountId} />}
        {currentModule === 'accounts' && <NightclubAccounts data={data} canDeliver={canDeliver} canRefund={canRefund} onGoToPOS={account => { setSelectedAccountId(account.id); setActiveModule('pos') }} onDeliverRound={(id, roundId) => run(() => onDeliverRound(id, roundId), 'Pedido entregado.')} onFinishAccount={id => run(() => onFinishAccount(id), 'Mesa libre.')} onRefundRound={(id, roundId, reason) => run(() => onRefundRound(id, roundId, reason), 'Pedido reembolsado.')} />}
        {currentModule === 'bar' && <NightclubBar data={data} onAdvance={(accountId, roundId) => run(() => onAdvanceRound(accountId, roundId), 'Estado de Barra actualizado.')} />}
        {currentModule === 'inventory' && <div className="space-y-5"><NightclubInventory data={data} onMovement={(id, quantity, type, reason) => run(() => onAdjustInventory(id, quantity, type, reason), 'Movimiento registrado.')} /><NightclubInventoryCosts data={data} onSave={item => run(() => onSaveInventory(item), 'Costo actualizado.')} /><NightclubCourtesyInventoryMovements data={data} /><section className="rounded-xl border border-slate-700 bg-slate-900 p-4"><h2 className="font-bold">Nuevo artículo de inventario</h2><p className="text-xs text-slate-400">Material físico que puede venderse directamente o formar parte de otro producto.</p><div className="mt-3 grid gap-2 sm:grid-cols-[1fr_140px_120px_auto]"><input aria-label="Nombre del artículo" placeholder="Nombre" value={newStockName} onChange={event => setNewStockName(event.target.value)} className="rounded-xl bg-slate-950 p-3" /><input aria-label="Stock inicial" type="number" min="0" placeholder="Stock inicial" value={newStockAmount} onChange={event => setNewStockAmount(event.target.value)} className="rounded-xl bg-slate-950 p-3" /><select aria-label="Unidad" value={newStockUnit} onChange={event => setNewStockUnit(event.target.value as typeof newStockUnit)} className="rounded-xl bg-slate-950 p-3"><option value="unit">Unidad</option><option value="ml">ml</option><option value="g">g</option></select><button onClick={() => run(() => { onSaveInventory({ id: crypto.randomUUID(), name: newStockName.trim(), unit: newStockUnit, current: Number(newStockAmount), minimum: 0 }); setNewStockName(''); setNewStockAmount('') }, 'Artículo creado.')} className="h-11 rounded-xl bg-amber-400 px-4 font-bold text-slate-950">Crear</button></div></section></div>}
        {currentModule === 'products' && <NightclubProducts data={data} onSave={product => run(() => onSaveProduct(product), 'Producto guardado.')} />}
        {currentModule === 'cash' && <NightclubCash data={data} onStartShift={amount => run(() => onStartShift(amount), 'Turno abierto.')} onCloseShift={counted => run(() => onCloseShift(counted), 'Turno cerrado y arqueo guardado.')} onCashMovement={draft => run(() => onCashMovement(draft), 'Movimiento registrado.')} />}
        {currentModule === 'history' && <div className="space-y-5"><Title title="Historial" subtitle="Cuentas cobradas, pagos y operaciones de la noche." /><div className="space-y-3">{closedAccounts.slice().reverse().map(account => <article key={account.id} className="rounded-xl border border-slate-800 bg-slate-900 p-4"><div className="flex justify-between gap-3"><strong>{nightclubAccountLabel(account, data)}</strong><b>{money(account.subtotal)}</b></div><p className="mt-1 text-xs text-slate-400">Pagado {money(nightclubPaidTotal(account))} · {(account.payments || (account.payment ? [account.payment] : [])).map(payment => payment.method.toUpperCase()).join(' + ')} · {account.paidAt ? new Date(account.paidAt).toLocaleString('es-BO') : ''}</p><p className="mt-1 text-xs text-slate-500">{account.rounds.length} rondas · Responsable {account.openedBy}</p></article>)}{!closedAccounts.length && <Empty text="Aún no hay cuentas cobradas." />}</div></div>}
        {currentModule === 'members' && <NightclubMembers data={data} role={normalizedRole} onSave={member => run(() => onSaveMember(member), 'Socio guardado.')} onRegister={value => run(() => onRegisterCourtesy(value), 'Cortesía registrada.')} onCancel={id => run(() => onCancelCourtesy(id), 'Cortesía anulada.')} />}
        {currentModule === 'customers' && <NightclubCustomers data={data} companyName={companyName} onSave={customer => run(() => onSaveCustomer(customer), 'Cliente guardado.')} />}
        {currentModule === 'users' && <div className="space-y-5"><Title title="Usuarios y roles" subtitle="Equipo del club vinculado a turnos y operaciones." /><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{(data.staff || []).map(person => <article key={person.id} className="rounded-xl border border-slate-800 bg-slate-900 p-4"><strong>{person.name}</strong><p className="text-sm text-slate-400">{person.role} · {person.active ? 'Activo' : 'Inactivo'}</p><button onClick={() => run(() => onSaveStaff({ ...person, active: !person.active }), 'Usuario actualizado.')} className="mt-2 text-xs text-amber-300">{person.active ? 'Desactivar' : 'Activar'}</button></article>)}</div><section className="rounded-xl border border-slate-800 bg-slate-900 p-4"><h2 className="font-bold">Añadir usuario local</h2><div className="mt-2 flex flex-wrap gap-2"><input aria-label="Nombre del usuario" placeholder="Nombre" value={staffName} onChange={event => setStaffName(event.target.value)} className="rounded-xl bg-slate-950 p-3" /><select aria-label="Rol del usuario" value={staffRole} onChange={event => setStaffRole(event.target.value as typeof staffRole)} className="rounded-xl bg-slate-950 p-3"><option value="service">Servicio</option><option value="cashier">Caja</option><option value="bar">Barra</option><option value="inventory">Inventario</option><option value="admin">Admin</option></select><button onClick={() => run(() => { if (!staffName.trim()) throw new Error('Ingresa un nombre.'); onSaveStaff({ id: crypto.randomUUID(), name: staffName.trim(), role: staffRole, active: true }); setStaffName('') }, 'Usuario creado.')} className="rounded-xl bg-amber-400 px-4 font-bold">Crear</button></div></section></div>}
        {currentModule === 'reports' && <div className="space-y-4"><NightclubReports data={data} companyName={companyName} /><NightclubCourtesyReport data={data} /></div>}
        {currentModule === 'settings' && <div className="space-y-5"><Title title="Configuración" subtitle="Gestiona zonas y mesas sin salir del flujo operativo." /><Panel title="Base configurada"><p className="text-sm text-slate-300">{data.zones.length} zonas · {data.tables.length} mesas · {data.products.length} productos · {data.inventory.length} insumos.</p></Panel><NightclubFloor data={data} onSelectTable={() => undefined} onSaveZone={draft => run(() => onSaveZone(draft), 'Zona guardada.')} onSaveTable={draft => run(() => onSaveTable(draft), 'Mesa guardada.')} /></div>}
      </main></div>
    {moreOpen && <div className="fixed inset-0 z-40 bg-black/60 lg:hidden" onClick={() => setMoreOpen(false)}><section aria-label="Más módulos" className="absolute inset-x-0 bottom-[65px] grid max-h-[65vh] grid-cols-2 gap-2 overflow-y-auto rounded-t-2xl border-t border-slate-700 bg-slate-900 p-4" onClick={event => event.stopPropagation()}>{moreModules.map(item => <button key={item.id} onClick={() => { setActiveModule(item.id); setMoreOpen(false) }} className={`flex min-h-12 items-center gap-3 rounded-xl border p-3 text-left text-sm font-semibold ${currentModule === item.id ? 'border-amber-400 bg-amber-400/10 text-amber-200' : 'border-slate-700'}`}><item.icon size={18} />{item.label}</button>)}</section></div>}
    <nav className="fixed inset-x-0 bottom-0 z-50 grid border-t border-slate-800 bg-slate-950 p-1 lg:hidden" style={{ gridTemplateColumns: `repeat(${mobileModules.length + (moreModules.length ? 1 : 0)}, minmax(0, 1fr))` }}>{mobileModules.map(item => <button key={item.id} onClick={() => { setActiveModule(item.id); setMoreOpen(false) }} className={`flex min-h-14 flex-col items-center justify-center gap-1 rounded-lg px-2 text-[10px] ${currentModule === item.id ? 'bg-amber-400 text-slate-950' : 'text-slate-400'}`}><item.icon size={17} />{item.label}</button>)}{moreModules.length > 0 && <button onClick={() => setMoreOpen(value => !value)} className={`flex min-h-14 flex-col items-center justify-center gap-1 rounded-lg px-2 text-[10px] ${moreOpen || moreModules.some(item => item.id === currentModule) ? 'bg-amber-400 text-slate-950' : 'text-slate-400'}`}><Menu size={17} />Más</button>}</nav>
    {courtesyAccountId !== null && <NightclubCourtesyDialog data={data} accountId={courtesyAccountId} onClose={() => setCourtesyAccountId(null)} onConfirm={value => run(() => onRegisterCourtesy(value), 'Cortesía registrada.')} />}
  </div>
}

function Title({ title, subtitle }: { title: string; subtitle: string }) { return <header><h1 className="text-2xl font-black sm:text-3xl">{title}</h1><p className="mt-1 text-sm text-slate-400">{subtitle}</p></header> }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><span className="text-xs text-slate-400">{label}</span><strong className="mt-2 block text-2xl">{value}</strong></div> }
function Panel({ title, children }: { title: string; children: ReactNode }) { return <section className="rounded-2xl border border-slate-800 bg-slate-950 p-4"><h2 className="mb-3 flex items-center gap-2 text-sm font-bold"><Sparkles size={15} className="text-amber-400" />{title}</h2>{children}</section> }
function Empty({ text }: { text: string }) { return <div className="rounded-xl border border-dashed border-slate-700 p-5 text-sm text-slate-400">{text}</div> }
