import type { NightclubDataset, NightclubRoundStatus } from '../domain/nightclubAccounts'
import { nightclubAccountLabel } from '../domain/nightclubAccounts'
import type { NightclubRoundDraft } from '../domain/nightclubAccounts'
import { useState } from 'react'
import { NightclubBarHistory } from './NightclubBarHistory'

const labels: Record<NightclubRoundStatus, string> = { pending: 'Pendiente', preparing: 'En preparaciÃ³n', ready: 'Listo', delivered: 'Entregado al mesero', cancelled: 'Anulado' }

export function NightclubBar({ data, role, actor, onAdvance, onCourtesy, onDiscount, onReverse }: { data: NightclubDataset; role: string; actor: string; onAdvance: (accountId: string, roundId: string) => void; onCourtesy: (accountId: string, draft: NightclubRoundDraft[], reason: string) => boolean; onDiscount: (accountId: string, amount: number, reason: string) => boolean; onReverse: (accountId: string, roundId: string, itemId: string, reason: string, kind: 'cancelled' | 'returned') => boolean }) {
  const [section, setSection] = useState<'pending' | 'history'>('pending')
  const rounds = data.accounts.filter(account => account.status !== 'closed').flatMap(account => account.rounds.filter(round => round.status !== 'delivered' && round.status !== 'cancelled' && round.items.some(item => item.preparationArea !== 'Directo')).map(round => ({ account, round })))
  return <div className="space-y-4"><header><h1 className="text-2xl font-black">Barra</h1><p className="text-sm text-slate-400">PreparaciÃ³n, entrega e historial de la jornada.</p></header><div className="flex gap-2 border-b border-slate-700 pb-2"><button onClick={() => setSection('pending')} className={`h-10 rounded-lg px-4 text-sm font-bold ${section === 'pending' ? 'bg-amber-400 text-slate-950' : 'bg-slate-800'}`}>Preparaciones</button><button onClick={() => setSection('history')} className={`h-10 rounded-lg px-4 text-sm font-bold ${section === 'history' ? 'bg-amber-400 text-slate-950' : 'bg-slate-800'}`}>Historial</button></div>{section === 'history' ? <NightclubBarHistory data={data} role={role} actor={actor} onCourtesy={onCourtesy} onDiscount={onDiscount} onReverse={onReverse} /> : <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{rounds.map(({account,round}) => <article key={round.id} className="rounded-xl border border-slate-700 bg-[#121b20] p-4"><div className="flex items-start justify-between"><div><strong>{nightclubAccountLabel(account, data)}</strong><span className="block text-xs text-slate-400">Ronda #{round.sequence} Â· {account.openedBy}</span></div><span className="rounded-full bg-slate-800 px-2 py-1 text-[11px] font-bold text-amber-200">{labels[round.status]}</span></div><div className="my-4 space-y-2">{round.items.filter(item => item.preparationArea !== 'Directo' && item.status !== 'cancelled' && item.status !== 'returned').map(item => <p key={item.id} className="flex justify-between border-b border-slate-800 pb-2 text-sm"><span>{item.quantity}Ã— {item.name}</span><span className="text-slate-500">Barra</span></p>)}</div><button onClick={() => onAdvance(account.id, round.id)} className="h-11 w-full rounded-xl bg-amber-400 font-bold text-slate-950">{round.status === 'pending' ? 'Iniciar preparaciÃ³n' : round.status === 'preparing' ? 'Marcar listo' : 'Entregar al mesero'}</button></article>)}{!rounds.length && <p className="rounded-xl border border-dashed border-slate-700 p-6 text-sm text-slate-400">No hay preparaciones pendientes.</p>}</div>}</div>
}
