import { useState } from 'react'
import type { NightclubDataset } from '../domain/nightclubAccounts'

export function NightclubInventory({ data, onAdjust }: { data: NightclubDataset; onAdjust: (id: string, current: number) => void }) {
  const [editing, setEditing] = useState<string | null>(null)
  const [value, setValue] = useState('')
  const [view, setView] = useState<'stock' | 'movements'>('stock')
  return <div className="space-y-5"><header><h1 className="text-2xl font-black">Inventario de barra</h1><p className="text-sm text-slate-400">El stock se descuenta al enviar cada ronda; incluye botellas, mixers y snacks.</p></header><div className="flex gap-2"><button onClick={() => setView('stock')} className={`rounded-xl px-4 py-2 text-sm font-bold ${view === 'stock' ? 'bg-purple-500' : 'bg-slate-800'}`}>Stock actual</button><button onClick={() => setView('movements')} className={`rounded-xl px-4 py-2 text-sm font-bold ${view === 'movements' ? 'bg-purple-500' : 'bg-slate-800'}`}>Movimientos</button></div>
    {view === 'stock' ? <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{data.inventory.map(item => <article key={item.id} className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><div className="flex justify-between gap-2"><strong>{item.name}</strong><span className={`text-xs font-bold ${item.current <= item.minimum ? 'text-amber-300' : 'text-emerald-300'}`}>{item.current <= item.minimum ? 'Stock bajo' : 'Disponible'}</span></div><p className="mt-3 text-2xl font-black">{item.current.toLocaleString('es-BO')} <small className="text-sm font-normal text-slate-400">{item.unit === 'unit' ? 'unid.' : item.unit}</small></p><p className="text-xs text-slate-400">Mínimo {item.minimum.toLocaleString('es-BO')} {item.unit}</p>{editing === item.id ? <div className="mt-3 flex gap-2"><input aria-label={`Nuevo stock de ${item.name}`} type="number" min="0" step="0.01" value={value} onChange={event => setValue(event.target.value)} className="min-w-0 flex-1 rounded-lg bg-slate-950 p-2" /><button onClick={() => { onAdjust(item.id, Number(value)); setEditing(null) }} className="rounded-lg bg-purple-500 px-3 text-sm font-bold">Guardar</button></div> : <button onClick={() => { setEditing(item.id); setValue(String(item.current)) }} className="mt-3 rounded-lg border border-slate-700 px-3 py-2 text-xs font-bold">Ajustar stock</button>}</article>)}{!data.inventory.length && <p className="text-sm text-slate-400">Crea el primer insumo en Productos.</p>}</div> : <div className="space-y-2">{(data.inventoryMovements || []).slice().reverse().map(item => <div key={item.id} className="flex flex-wrap justify-between gap-2 rounded-xl border border-slate-800 bg-slate-900 p-3 text-sm"><span>{data.inventory.find(stock => stock.id === item.inventoryId)?.name || item.inventoryId}<small className="ml-2 text-slate-400">{item.type === 'sale' ? 'Ronda' : 'Ajuste'} · {new Date(item.at).toLocaleString('es-BO')}</small></span><b className={item.quantity < 0 ? 'text-amber-300' : 'text-emerald-300'}>{item.quantity > 0 ? '+' : ''}{item.quantity.toLocaleString('es-BO')} {data.inventory.find(stock => stock.id === item.inventoryId)?.unit}</b></div>)}{!(data.inventoryMovements || []).length && <p className="text-slate-400">Sin movimientos todavía.</p>}</div>}
  </div>
}
