import { Minus, Plus, Search, ShoppingBag, X } from 'lucide-react'
import { useMemo, useState } from 'react'
import type { NightclubDataset, NightclubRoundDraft, NightclubServiceTarget } from '../domain/nightclubAccounts'
import { nightclubAccountLabel, nightclubBalance, nightclubProductAvailability } from '../domain/nightclubAccounts'

const money = (value: number) => `Bs ${value.toLocaleString('es-BO', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`

export function NightclubPOS({ data, draft, selectedAccountId, onSelectAccount, onDraftChange, onOpenAccount, onSendRound }: {
  data: NightclubDataset
  draft: NightclubRoundDraft[]
  selectedAccountId: string
  onSelectAccount: (id: string) => void
  onDraftChange: (draft: NightclubRoundDraft[]) => void
  onOpenAccount: (target: NightclubServiceTarget) => void
  onSendRound: (accountId: string, draft: NightclubRoundDraft[]) => void
}) {
  const [category, setCategory] = useState('Todos')
  const [search, setSearch] = useState('')
  const [drawerOpen, setDrawerOpen] = useState(false)
  const [targetType, setTargetType] = useState<'table' | 'customer'>('table')
  const [tableId, setTableId] = useState(data.tables.find(table => table.status === 'available')?.id || '')
  const [customerId, setCustomerId] = useState('')
  const [customerName, setCustomerName] = useState('')
  const accounts = data.accounts.filter(account => account.status !== 'closed')
  const selected = accounts.find(account => account.id === selectedAccountId) || accounts[0]
  const categories = ['Todos', ...new Set(data.products.filter(item => item.active !== false).map(item => item.category))]
  const products = useMemo(() => data.products.filter(product => product.active !== false && (category === 'Todos' || product.category === category) && product.name.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase())), [category, data.products, search])
  const itemCount = draft.reduce((sum, item) => sum + item.quantity, 0)
  const draftTotal = draft.reduce((sum, item) => sum + (data.products.find(product => product.id === item.productId)?.price || 0) * item.quantity, 0)
  const update = (productId: string, delta: number) => onDraftChange((draft.some(item => item.productId === productId) ? draft.map(item => item.productId === productId ? { ...item, quantity: item.quantity + delta } : item) : [...draft, { productId, quantity: delta }]).filter(item => item.quantity > 0))
  const createAccount = () => {
    if (targetType === 'table') onOpenAccount({ type: 'table', tableId })
    else {
      const customer = data.customers.find(item => item.id === customerId)
      const displayName = customer?.name || customerName.trim()
      if (!displayName) throw new Error('Escribe o selecciona el nombre del cliente.')
      if (!window.confirm(`Esta cuenta quedará registrada a nombre de ${displayName} y no estará asociada a una mesa. ¿Deseas continuar?`)) return
      onOpenAccount({ type: 'customer', customerId: customer?.id, displayName })
    }
  }

  const accountPanel = (mobile = false) => <section className={`${mobile ? 'max-h-[88vh] overflow-y-auto pb-8' : 'sticky top-20 max-h-[calc(100vh-6rem)] overflow-y-auto'} border-l border-slate-700 bg-[#121b20] p-4`}>
    <div className="flex items-center justify-between gap-3"><div><span className="text-[11px] font-bold uppercase tracking-wider text-amber-300">Cuenta activa</span><h2 className="text-lg font-bold">{selected ? nightclubAccountLabel(selected, data) : 'Nueva cuenta'}</h2></div>{mobile && <button aria-label="Cerrar cuenta" onClick={() => setDrawerOpen(false)} className="grid h-11 w-11 place-items-center rounded-xl border border-slate-700"><X /></button>}</div>
    {accounts.length > 0 && <select aria-label="Cuenta activa" value={selected?.id || ''} onChange={event => { onSelectAccount(event.target.value); onDraftChange([]) }} className="mt-3 w-full rounded-lg border border-slate-700 bg-slate-950 p-3 text-sm">{accounts.map(account => <option key={account.id} value={account.id}>{nightclubAccountLabel(account, data)} · {money(nightclubBalance(account))}</option>)}</select>}
    {!selected && <div className="mt-4 space-y-3 rounded-xl border border-slate-700 p-3"><div className="grid grid-cols-2 gap-2"><button onClick={() => setTargetType('table')} className={`h-11 rounded-lg text-sm font-bold ${targetType === 'table' ? 'bg-amber-400 text-slate-950' : 'bg-slate-800'}`}>Mesa</button><button onClick={() => setTargetType('customer')} className={`h-11 rounded-lg text-sm font-bold ${targetType === 'customer' ? 'bg-amber-400 text-slate-950' : 'bg-slate-800'}`}>Sin mesa</button></div>{targetType === 'table' ? <select aria-label="Mesa para nueva cuenta" value={tableId} onChange={event => setTableId(event.target.value)} className="w-full rounded-lg bg-slate-950 p-3 text-sm">{data.tables.filter(table => table.status === 'available').map(table => <option key={table.id} value={table.id}>{table.name} · {data.zones.find(zone => zone.id === table.zoneId)?.name} · Libre</option>)}</select> : <><select aria-label="Cliente existente" value={customerId} onChange={event => { setCustomerId(event.target.value); if (event.target.value) setCustomerName('') }} className="w-full rounded-lg bg-slate-950 p-3 text-sm"><option value="">Cliente nuevo</option>{data.customers.filter(item => item.active !== false).map(customer => <option key={customer.id} value={customer.id}>{customer.name}</option>)}</select>{!customerId && <input aria-label="Nombre para cuenta personal" value={customerName} onChange={event => setCustomerName(event.target.value)} placeholder="Nombre del cliente" className="w-full rounded-lg bg-slate-950 p-3 text-sm" />}</>}<button disabled={data.shift?.status !== 'open' || (targetType === 'table' && !tableId)} onClick={createAccount} className="h-11 w-full rounded-lg bg-amber-400 font-bold text-slate-950 disabled:opacity-40">Abrir cuenta</button></div>}
    {selected && <><div className="mt-4 space-y-2">{draft.map(line => { const product = data.products.find(item => item.id === line.productId); return <div key={line.productId} className="grid grid-cols-[1fr_auto] gap-3 border-b border-slate-800 py-3"><div><strong className="text-sm">{product?.name}</strong><span className="block text-xs text-slate-400">{money((product?.price || 0) * line.quantity)}</span></div><div className="flex items-center gap-2"><button aria-label={`Quitar ${product?.name}`} onClick={() => update(line.productId, -1)} className="grid h-9 w-9 place-items-center rounded-lg bg-slate-800"><Minus size={15} /></button><b>{line.quantity}</b><button aria-label={`Agregar ${product?.name}`} onClick={() => update(line.productId, 1)} className="grid h-9 w-9 place-items-center rounded-lg bg-slate-800"><Plus size={15} /></button></div></div>})}{!draft.length && <p className="rounded-lg border border-dashed border-slate-700 p-4 text-sm text-slate-400">Selecciona productos para preparar una nueva ronda.</p>}</div><div className="mt-4 flex items-center justify-between"><span className="text-sm text-slate-400">Subtotal de ronda</span><strong className="text-xl">{money(draftTotal)}</strong></div><button disabled={!draft.length || selected.status !== 'open'} onClick={() => { onSendRound(selected.id, draft); onDraftChange([]); setDrawerOpen(false) }} className="mt-4 h-12 w-full rounded-xl bg-amber-400 font-black text-slate-950 disabled:opacity-40">ENVIAR RONDA</button>{selected.status === 'bill_requested' && <p className="mt-3 text-sm text-amber-300">Esta cuenta está por cobrar. Reábrela desde Cuentas para añadir productos.</p>}</>}
  </section>

  return <div className="space-y-3"><header><h1 className="text-2xl font-black">POS</h1><p className="text-sm text-slate-400">Registra una ronda sin perder de vista la cuenta.</p></header><div className="grid min-h-[640px] overflow-hidden rounded-2xl border border-slate-700 bg-[#0d1519] lg:grid-cols-[minmax(0,2fr)_minmax(320px,1fr)]"><section className="min-w-0 p-3 sm:p-5"><div className="flex gap-2 overflow-x-auto pb-2">{categories.map(item => <button key={item} onClick={() => setCategory(item)} className={`h-11 shrink-0 rounded-full px-4 text-xs font-bold ${category === item ? 'bg-amber-400 text-slate-950' : 'bg-slate-800 text-slate-200'}`}>{item}</button>)}</div><label className="mt-2 flex h-11 items-center gap-2 rounded-xl border border-slate-700 bg-slate-950 px-3"><Search size={17} className="text-slate-400" /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Buscar producto" className="min-w-0 flex-1 bg-transparent text-sm outline-none" /></label><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3 xl:grid-cols-4">{products.map(product => { const available = nightclubProductAvailability(product, data.inventory); const quantity = draft.find(item => item.productId === product.id)?.quantity || 0; return <button key={product.id} disabled={!selected || selected.status !== 'open' || available <= quantity} onClick={() => update(product.id, 1)} className="min-h-36 overflow-hidden rounded-xl border border-slate-700 bg-slate-900 text-left disabled:opacity-40"><div className="h-20 bg-slate-800">{product.imageUrl ? <img src={product.imageUrl} alt="" className="h-full w-full object-cover" /> : <div className="grid h-full place-items-center text-slate-500"><ShoppingBag /></div>}</div><div className="p-3"><strong className="line-clamp-2 text-sm">{product.name}</strong><span className="mt-1 block text-sm font-black text-amber-300">{money(product.price)}</span></div></button>})}</div></section><div className="hidden lg:block">{accountPanel()}</div></div><button onClick={() => setDrawerOpen(true)} className="fixed inset-x-3 bottom-16 z-30 flex h-14 items-center justify-between rounded-2xl bg-amber-400 px-4 font-bold text-slate-950 shadow-xl lg:hidden"><span>Cuenta · {itemCount} productos</span><span>{money(draftTotal)}</span></button>{drawerOpen && <div className="fixed inset-0 z-[60] bg-black/60 lg:hidden" onClick={() => setDrawerOpen(false)}><div className="absolute inset-x-0 bottom-0 max-h-[88vh] rounded-t-3xl bg-[#121b20]" onClick={event => event.stopPropagation()}>{accountPanel(true)}</div></div>}</div>
}
