import { useState } from 'react'
import type { NightclubDataset, NightclubTable } from '../domain/nightclubAccounts'
import type { TableDraft, ZoneDraft } from '../domain/nightclubFloor'

const money = (value: number) => `Bs ${value.toLocaleString('es-BO', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`

export function NightclubFloor({ data, onSelectTable, onSaveZone, onSaveTable }: {
  data: NightclubDataset
  onSelectTable: (id: string) => void
  onSaveZone: (draft: ZoneDraft) => boolean
  onSaveTable: (draft: TableDraft) => boolean
}) {
  const [zoneDraft, setZoneDraft] = useState<ZoneDraft | null>(null)
  const [tableDraft, setTableDraft] = useState<TableDraft | null>(null)
  const [managing, setManaging] = useState(false)
  const newTable = (zoneId: string): TableDraft => ({ id: '', name: '', zoneId, capacity: 4, status: 'available' })
  const saveZone = () => { if (zoneDraft && onSaveZone(zoneDraft)) setZoneDraft(null) }
  const saveTable = () => { if (tableDraft && onSaveTable(tableDraft)) setTableDraft(null) }
  return <div className="space-y-6">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-black">Salón, VIP y reservados</h1><p className="text-sm text-slate-400">Selecciona una mesa para ver su cuenta y añadir rondas.</p></div><button onClick={() => setManaging(value => !value)} className="rounded-xl border border-purple-500 px-4 py-2 text-sm font-bold text-purple-200">{managing ? 'Terminar edición' : 'Administrar salón'}</button></header>
    {managing && <button onClick={() => setZoneDraft({ id: '', name: '' })} className="rounded-xl bg-purple-500 px-4 py-2 text-sm font-bold">+ Nueva zona</button>}
    {data.zones.slice().sort((a, b) => a.sortOrder - b.sortOrder).map(zone => {
      const tables = data.tables.filter(table => table.zoneId === zone.id)
      return <section key={zone.id}><div className="mb-3 flex flex-wrap items-center gap-2"><h2 className="mr-auto text-sm font-bold uppercase tracking-wider text-purple-300">{zone.name}</h2>{managing && <><button onClick={() => setZoneDraft({ id: zone.id, name: zone.name })} className="rounded-lg border border-slate-700 px-3 py-1.5 text-xs">Editar zona</button><button onClick={() => setTableDraft(newTable(zone.id))} className="rounded-lg bg-purple-500 px-3 py-1.5 text-xs font-bold">+ Nueva mesa</button></>}</div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{tables.map(table => {
        const account = data.accounts.find(item => item.id === table.activeAccountId && item.status !== 'closed')
        return <article key={table.id} className={`rounded-2xl border p-4 ${table.status === 'available' ? 'border-emerald-800 bg-emerald-950/20' : table.status === 'reserved' ? 'border-indigo-700 bg-indigo-950/30' : table.status === 'bill_requested' ? 'border-amber-500 bg-amber-950/30' : 'border-purple-600 bg-purple-950/30'}`}><button onClick={() => onSelectTable(table.id)} className="w-full text-left"><span className="text-[10px] font-bold uppercase text-slate-400">{table.status === 'available' ? 'Libre' : table.status === 'reserved' ? 'Reservada' : table.status === 'bill_requested' ? 'Por cobrarse' : 'Ocupada'}</span><strong className="mt-1 block text-lg">{table.name}</strong><span className="text-xs text-slate-400">{table.capacity} personas</span>{account && <strong className="mt-3 block text-purple-200">{money(account.subtotal)} · {account.rounds.length} rondas</strong>}{table.reservationName && <span className="mt-2 block text-xs text-indigo-200">{table.reservationName}</span>}</button>{managing && <button onClick={() => setTableDraft({ id: table.id, name: table.name, zoneId: table.zoneId, capacity: table.capacity, status: table.status })} className="mt-3 rounded-lg border border-slate-700 px-3 py-1.5 text-xs">Editar mesa</button>}</article>
      })}{!tables.length && <p className="text-sm text-slate-400">Todavía no hay mesas en esta zona.</p>}</div></section>
    })}
    {zoneDraft && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/80 p-4"><section role="dialog" aria-modal="true" aria-label="Zona" className="w-full max-w-sm space-y-3 rounded-2xl border border-slate-700 bg-slate-900 p-5"><h2 className="text-lg font-bold">{zoneDraft.id ? 'Editar zona' : 'Nueva zona'}</h2><input autoFocus aria-label="Nombre de la zona" placeholder="Nombre de la zona" value={zoneDraft.name} onChange={event => setZoneDraft({ ...zoneDraft, name: event.target.value })} className="w-full rounded-xl bg-slate-950 p-3" /><div className="flex gap-2"><button onClick={() => setZoneDraft(null)} className="flex-1 rounded-xl border border-slate-700 p-3">Cancelar</button><button onClick={saveZone} disabled={!zoneDraft.name.trim()} className="flex-1 rounded-xl bg-purple-500 p-3 font-bold disabled:opacity-40">Guardar</button></div></section></div>}
    {tableDraft && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/80 p-4"><section role="dialog" aria-modal="true" aria-label="Mesa" className="w-full max-w-sm space-y-3 rounded-2xl border border-slate-700 bg-slate-900 p-5"><h2 className="text-lg font-bold">{tableDraft.id ? 'Editar mesa' : 'Nueva mesa'}</h2><input autoFocus aria-label="Nombre de la mesa" placeholder="Mesa 12 o VIP 3" value={tableDraft.name} onChange={event => setTableDraft({ ...tableDraft, name: event.target.value })} className="w-full rounded-xl bg-slate-950 p-3" /><label className="block text-xs text-slate-400">Zona<select aria-label="Zona de la mesa" value={tableDraft.zoneId} onChange={event => setTableDraft({ ...tableDraft, zoneId: event.target.value })} className="mt-1 w-full rounded-xl bg-slate-950 p-3 text-sm text-white">{data.zones.map(zone => <option key={zone.id} value={zone.id}>{zone.name}</option>)}</select></label><label className="block text-xs text-slate-400">Capacidad<input aria-label="Capacidad de la mesa" type="number" min="1" max="100" value={tableDraft.capacity} onChange={event => setTableDraft({ ...tableDraft, capacity: Number(event.target.value) })} className="mt-1 w-full rounded-xl bg-slate-950 p-3 text-sm text-white" /></label>{tableDraft.id && <label className="block text-xs text-slate-400">Estado<select aria-label="Estado de la mesa" value={tableDraft.status} disabled={!!data.tables.find(table => table.id === tableDraft.id)?.activeAccountId} onChange={event => setTableDraft({ ...tableDraft, status: event.target.value as NightclubTable['status'] })} className="mt-1 w-full rounded-xl bg-slate-950 p-3 text-sm text-white disabled:opacity-50"><option value="available">Libre</option><option value="reserved">Reservada</option>{!!data.tables.find(table => table.id === tableDraft.id)?.activeAccountId && <><option value="occupied">Ocupada</option><option value="bill_requested">Por cobrarse</option></>}</select></label>}<div className="flex gap-2"><button onClick={() => setTableDraft(null)} className="flex-1 rounded-xl border border-slate-700 p-3">Cancelar</button><button onClick={saveTable} disabled={!tableDraft.name.trim() || !tableDraft.zoneId || tableDraft.capacity < 1} className="flex-1 rounded-xl bg-purple-500 p-3 font-bold disabled:opacity-40">Guardar</button></div></section></div>}
  </div>
}
