import { useRef, useState } from 'react'
import type { NightclubAccount, NightclubPaymentDraft } from '../domain/nightclubAccounts'
import { nightclubBalance, nightclubPaidTotal } from '../domain/nightclubAccounts'

const money = (value: number) => `Bs ${value.toFixed(2)}`
export function NightclubAccountPayment({ account, onClose, onPay }: { account: NightclubAccount; onClose: () => void; onPay: (payment: NightclubPaymentDraft) => boolean }) {
  const balance = nightclubBalance(account); const [method, setMethod] = useState<'cash' | 'qr' | 'card'>('cash'); const [partial, setPartial] = useState(false); const [amount, setAmount] = useState(String(balance)); const [received, setReceived] = useState(String(balance)); const operation = useRef<string | null>(null); const busy = useRef(false)
  const value = partial ? Number(amount) : balance; const cashReceived = Number(received); const valid = Number.isFinite(value) && value > 0 && value <= balance && (method !== 'cash' || Number.isFinite(cashReceived) && cashReceived >= value)
  const pay = () => { if (!valid || busy.current) return; busy.current = true; const operationId = operation.current ||= crypto.randomUUID(); const ok = onPay({ method, amount: value, ...(method === 'cash' ? { received: cashReceived } : {}), operationId }); busy.current = false; if (ok) onClose() }
  return <div className="fixed inset-0 z-[70] grid place-items-center bg-black/75 p-4"><section className="w-full max-w-md space-y-4 rounded-2xl border border-emerald-400/30 bg-slate-900 p-5"><div className="flex justify-between"><h2 className="text-xl font-black">Cobrar cuenta</h2><button onClick={onClose}>×</button></div><div className="grid grid-cols-3 gap-2 rounded-xl bg-slate-950 p-3 text-xs"><span>Total<strong className="block">{money(account.subtotal)}</strong></span><span>Pagado<strong className="block text-emerald-300">{money(nightclubPaidTotal(account))}</strong></span><span>Saldo<strong className="block text-amber-300">{money(balance)}</strong></span></div><p className="rounded-xl bg-emerald-400/10 p-3">Saldo a cobrar: <b>{money(balance)}</b></p><div className="grid grid-cols-3 gap-2">{([['cash','Efectivo'],['qr','QR'],['card','Tarjeta']] as const).map(([id,label]) => <button key={id} onClick={() => setMethod(id)} className={`min-h-11 rounded-xl border ${method === id ? 'bg-emerald-300 text-slate-950' : 'border-slate-600'}`}>{label}</button>)}</div><label className="flex gap-2 text-sm"><input type="checkbox" checked={partial} onChange={e => { setPartial(e.target.checked); setAmount(String(e.target.checked ? 0 : balance)); setReceived(String(e.target.checked ? 0 : balance)); operation.current = null }} /> Pago parcial o dividido</label>{partial && <label>Monto a cobrar<input type="number" value={amount} onChange={e => setAmount(e.target.value)} className="mt-1 w-full rounded-xl bg-slate-950 p-3" /></label>}{method === 'cash' && <label>Recibido<input type="number" value={received} onChange={e => setReceived(e.target.value)} className="mt-1 w-full rounded-xl bg-slate-950 p-3" /><small>Cambio: {money(Math.max(0, cashReceived - value))}</small></label>}<div className="flex gap-2"><button onClick={onClose} className="flex-1 rounded-xl border p-3">Cancelar</button><button disabled={!valid} onClick={pay} className="flex-1 rounded-xl bg-emerald-400 p-3 font-bold text-slate-950 disabled:opacity-40">{method === 'cash' ? 'Confirmar pago' : 'Confirmar pago recibido'}</button></div><p className="text-xs text-slate-400">QR y Tarjeta requieren confirmación del operador; no verifican una transacción bancaria.</p></section></div>
}
