import { useState } from 'react'
import type { NightclubDataset, NightclubInventoryItem } from '../domain/nightclubAccounts'
import { formatInventoryQuantity } from '../../shared/domain/inventoryUnits'

type Category = 'Licores' | 'Cervezas' | 'Refrescos' | 'Piqueos' | 'Cocina / Insumos' | 'Otro'
type BottleDraft = { id?: string; name: string; category: string; closedBottles: number; minimum: number; capacityMl: number; capacityUnit: 'ml' | 'l'; cost: number; sellBottle: boolean; bottlePrice: number; sellPour: boolean; pourMl: number; pourPrice: number }
type SimpleDraft = { name: string; category: Category; quantity: number; minimum: number; unit: 'unit' | 'ml' | 'g' | 'l' | 'kg'; cost: number; price: number; presentation: string; sell: boolean }
const choices: Array<{ id: Category; icon: string; detail: string }> = [{ id: 'Licores', icon: String.fromCodePoint(0x1f37e), detail: 'Botella y vaso' }, { id: 'Cervezas', icon: String.fromCodePoint(0x1f37a), detail: 'Botella o lata' }, { id: 'Refrescos', icon: String.fromCodePoint(0x1f964), detail: 'Botella, lata o jarra' }, { id: 'Piqueos', icon: String.fromCodePoint(0x1f35f), detail: 'Unidad o receta' }, { id: 'Cocina / Insumos', icon: String.fromCodePoint(0x1f373), detail: 'Kg, g, litros o ml' }, { id: 'Otro', icon: String.fromCodePoint(0x1f4e6), detail: 'Existencia general' }]
const bottleBlank = (category = 'Licores'): BottleDraft => ({ name: '', category, closedBottles: 0, minimum: 0, capacityMl: category === 'Refrescos' ? 2000 : 750, capacityUnit: category === 'Refrescos' ? 'l' : 'ml', cost: 0, sellBottle: category !== 'Refrescos', bottlePrice: 0, sellPour: category === 'Licores' || category === 'Refrescos', pourMl: category === 'Refrescos' ? 1000 : 50, pourPrice: 0 })
const simpleBlank = (category: Category): SimpleDraft => ({ name: '', category, quantity: 0, minimum: 0, unit: category === 'Cocina / Insumos' ? 'g' : 'unit', cost: 0, price: 0, presentation: category === 'Cervezas' ? 'Botella' : 'Unidad', sell: category !== 'Cocina / Insumos' })
const money = (n: number) => `Bs ${n.toFixed(2)}`

export function NightclubBottleInventory({ data, onSave, onSaveSimple, onOpenBottle, onExit }: { data: NightclubDataset; onSave: (draft: BottleDraft) => void; onSaveSimple: (draft: SimpleDraft) => void; onOpenBottle: (id: string) => void; onExit: (id: string, ml: number, type: 'waste' | 'courtesy' | 'internal_consumption', reason: string) => void }) {
  const [filter, setFilter] = useState<Category | 'Todos'>('Todos'); const [chooser, setChooser] = useState(false); const [bottle, setBottle] = useState<BottleDraft | null>(null); const [simple, setSimple] = useState<SimpleDraft | null>(null); const [exit, setExit] = useState<NightclubInventoryItem | null>(null); const [ml, setMl] = useState('')
  const items = data.inventory.filter(item => filter === 'Todos' || item.category === filter)
  const missingSalePrice = !!bottle && ((bottle.sellBottle && (!Number.isFinite(bottle.bottlePrice) || bottle.bottlePrice <= 0)) || (bottle.sellPour && (!Number.isFinite(bottle.pourPrice) || bottle.pourPrice <= 0)))
  return <section className="space-y-4"><header className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-black">Productos de inventario</h1><p className="text-sm text-slate-400">Existencia física y presentaciones POS vinculadas.</p></div><button onClick={() => setChooser(true)} className="h-10 rounded-xl bg-amber-300 px-3 text-sm font-bold text-slate-950">+ Nuevo producto de inventario</button></header><div className="flex flex-wrap gap-2">{(['Todos', ...choices.map(x => x.id)] as Array<Category | 'Todos'>).map(value => <button key={value} onClick={() => setFilter(value)} className={`rounded-full px-3 py-1.5 text-xs font-bold ${filter === value ? 'bg-amber-300 text-slate-950' : 'bg-slate-800 text-slate-300'}`}>{value}</button>)}</div><div className="grid gap-3 lg:grid-cols-2">{items.map(item => { const products = data.products.filter(p => p.active !== false && (p.bottlePresentation?.inventoryId === item.id || item.linkedProductIds?.includes(p.id))); const open = item.openBottleMl || 0; return <article key={item.id} className="rounded-2xl border border-white/10 bg-[#0d1720] p-4"><div className="flex justify-between gap-3"><div><span className="text-xs font-bold text-amber-200">{item.category || 'Otro'}</span><h2 className="mt-1 font-bold">{item.name.toUpperCase()}</h2><p className="mt-1 text-sm text-slate-300">{item.bottleCapacityMl ? `${item.current} botellas cerradas` : formatInventoryQuantity(item.current, item.displayUnit || item.unit, item.unit === 'unit' ? 'unidades' : undefined)}</p>{item.bottleCapacityMl && <p className="text-xs text-slate-400">{open ? `1 abierta: ${open} / ${item.bottleCapacityMl} ml` : 'Sin botella abierta'}</p>}</div>{item.bottleCapacityMl && <div className="space-y-2"><button disabled={open > 0 || item.current < 1} onClick={() => onOpenBottle(item.id)} className="block rounded-lg border border-amber-300/50 px-3 py-2 text-xs font-bold text-amber-200 disabled:opacity-40">Abrir botella</button><button onClick={() => { setExit(item); setMl('') }} className="block rounded-lg border border-slate-600 px-3 py-2 text-xs font-bold">Salida</button></div>}</div>{products.length > 0 && <div className="mt-3 border-t border-white/10 pt-3 text-xs">{products.map(product => <span key={product.id} className="mr-2 inline-block rounded-full bg-slate-900 px-2 py-1">{product.name.replace(`${item.name} - `, '')} · {money(product.price)}</span>)}</div>}</article>})}</div>{!items.length && <p className="rounded-xl border border-dashed border-slate-700 p-5 text-sm text-slate-400">No hay productos en esta categoría.</p>}
    {chooser && <Modal title="¿Qué tipo de producto quieres registrar?" onClose={() => setChooser(false)}><div className="grid gap-2 sm:grid-cols-2">{choices.map(choice => <button key={choice.id} onClick={() => { setChooser(false); if (choice.id === 'Licores' || choice.id === 'Refrescos') setBottle(bottleBlank(choice.id)); else setSimple(simpleBlank(choice.id)) }} className="rounded-xl border border-white/10 bg-slate-900 p-4 text-left"><strong>{choice.icon} {choice.id}</strong><span className="block text-xs text-slate-400">{choice.detail}</span></button>)}</div></Modal>}
    {bottle && <Modal title={bottle.category === 'Licores' ? 'Nuevo licor' : 'Nuevo refresco'} onClose={() => setBottle(null)}>
      <p className="mb-4 text-sm text-slate-400">La existencia se guarda una vez y las presentaciones se vinculan solas.</p>
      <div className="grid gap-3 sm:grid-cols-2"><Text label="Nombre" value={bottle.name} onChange={value => setBottle({ ...bottle, name: value })} /><NumericField label="Cantidad" value={bottle.closedBottles} onChange={value => setBottle({ ...bottle, closedBottles: value })} /><BottleContentField bottle={bottle} onChange={setBottle} /><NumericField label="Costo por botella" value={bottle.cost} onChange={value => setBottle({ ...bottle, cost: value })} /></div>
      <div className="mt-4 space-y-3"><b>¿Cómo lo vendes?</b><Check label="Botella" checked={bottle.sellBottle} onChange={checked => setBottle({ ...bottle, sellBottle: checked })}>{bottle.sellBottle && <NumericField label="Precio botella" value={bottle.bottlePrice} onChange={value => setBottle({ ...bottle, bottlePrice: value })} />}</Check><Check label={bottle.category === 'Licores' ? 'Vaso' : 'Jarra'} checked={bottle.sellPour} onChange={checked => setBottle({ ...bottle, sellPour: checked })}>{bottle.sellPour && <div className="grid grid-cols-2 gap-2"><NumericField label="Medida (ml)" value={bottle.pourMl} onChange={value => setBottle({ ...bottle, pourMl: value })} /><NumericField label="Precio" value={bottle.pourPrice} onChange={value => setBottle({ ...bottle, pourPrice: value })} /></div>}</Check></div>
      {missingSalePrice && <p role="alert" className="mt-3 text-sm font-semibold text-amber-200">Ingresa un precio para vender esta presentación.</p>}
      <Actions disabled={missingSalePrice} onCancel={() => setBottle(null)} onSave={() => { if (!missingSalePrice) { onSave(bottle); setBottle(null) } }} />
    </Modal>}
    {simple && <Modal title={`Nuevo ${simple.category}`} onClose={() => setSimple(null)}><div className="grid gap-3 sm:grid-cols-2"><Text label="Nombre" value={simple.name} onChange={value => setSimple({ ...simple, name: value })} /><NumericField label="Cantidad" value={simple.quantity} onChange={value => setSimple({ ...simple, quantity: value })} /><label className="text-sm">Presentación<select value={simple.presentation} onChange={e => setSimple({ ...simple, presentation: e.target.value })} className="mt-1 w-full rounded-xl bg-slate-950 p-3">{(simple.category === 'Cervezas' ? ['Botella', 'Lata'] : ['Unidad']).map(value => <option key={value}>{value}</option>)}</select></label><NumericField label="Costo unitario" value={simple.cost} onChange={value => setSimple({ ...simple, cost: value })} />{simple.category === 'Cocina / Insumos' && <label className="text-sm">Unidad<select value={simple.unit} onChange={e => setSimple({ ...simple, unit: e.target.value as SimpleDraft['unit'] })} className="mt-1 w-full rounded-xl bg-slate-950 p-3"><option value="kg">Kilogramos</option><option value="g">Gramos</option><option value="l">Litros</option><option value="ml">Mililitros</option><option value="unit">Unidades</option></select></label>}<Check label="Crear presentación para POS" checked={simple.sell} onChange={checked => setSimple({ ...simple, sell: checked })}>{simple.sell && <NumericField label="Precio de venta" value={simple.price} onChange={value => setSimple({ ...simple, price: value })} />}</Check></div><Actions onCancel={() => setSimple(null)} onSave={() => { onSaveSimple(simple); setSimple(null) }} /></Modal>}
    {exit && <Modal title="Registrar salida de botella abierta" onClose={() => setExit(null)}><p className="text-sm text-slate-400">Disponible: {exit.openBottleMl || 0} ml</p><NumericField label="Mililitros" value={Number(ml)} onChange={value => setMl(String(value))} /><Actions onCancel={() => setExit(null)} onSave={() => { onExit(exit.id, Number(ml), 'waste', 'Salida registrada'); setExit(null) }} /></Modal>}</section>
}
function Modal({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><section role="dialog" aria-modal="true" aria-label={title} className="max-h-[94vh] w-full max-w-xl overflow-y-auto rounded-2xl bg-[#121b20] p-5"><h2 className="text-xl font-black">{title}</h2>{children}<button onClick={onClose} className="sr-only">Cerrar</button></section></div> }
function Text({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="text-sm">{label}<input value={value} onChange={e => onChange(e.target.value)} className="mt-1 w-full rounded-xl bg-slate-950 p-3" /></label> }
function NumericField({ label, value, onChange }: { label: string; value: number; onChange: (value: number) => void }) { return <label className="block text-sm">{label}<input type="number" min="0" value={value} onChange={e => onChange(Number(e.target.value))} className="mt-1 w-full rounded-xl bg-slate-950 p-3" /></label> }
function BottleContentField({ bottle, onChange }: { bottle: BottleDraft; onChange: (next: BottleDraft) => void }) { const multiplier = bottle.capacityUnit === 'l' ? 1000 : 1; return <label className="block text-sm">Contenido por botella<div className="mt-1 flex gap-2"><input aria-label="Contenido por botella" type="number" min="0" step={bottle.capacityUnit === 'l' ? '0.1' : '1'} value={bottle.capacityMl / multiplier} onChange={event => onChange({ ...bottle, capacityMl: Number(event.target.value) * multiplier })} className="min-w-0 flex-1 rounded-xl bg-slate-950 p-3" /><select aria-label="Unidad de contenido por botella" value={bottle.capacityUnit} onChange={event => onChange({ ...bottle, capacityUnit: event.target.value as BottleDraft['capacityUnit'] })} className="rounded-xl bg-slate-950 p-3"><option value="ml">ml</option><option value="l">L</option></select></div></label> }
function Check({ label, checked, onChange, children }: { label: string; checked: boolean; onChange: (checked: boolean) => void; children: React.ReactNode }) { return <label className="block rounded-xl bg-slate-900 p-3"><input type="checkbox" checked={checked} onChange={e => onChange(e.target.checked)} /> <strong className="ml-2">{label}</strong>{checked && <div className="mt-3">{children}</div>}</label> }
function Actions({ onCancel, onSave, disabled = false }: { onCancel: () => void; onSave: () => void; disabled?: boolean }) { return <div className="mt-5 flex gap-2"><button onClick={onCancel} className="h-11 flex-1 rounded-xl border border-slate-600">Cancelar</button><button disabled={disabled} onClick={onSave} className="h-11 flex-1 rounded-xl bg-amber-300 font-bold text-slate-950 disabled:cursor-not-allowed disabled:opacity-40">Guardar</button></div> }
