import { useMemo, useState } from 'react'
import type { NightclubCourtesyDraft, NightclubDataset, NightclubMember } from '../domain/nightclubAccounts'
import { courtesyBalance } from '../domain/nightclubCourtesies'

const money = (value: number) => `Bs ${value.toLocaleString('es-BO', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
const input = 'w-full rounded-xl border border-slate-700 bg-slate-950 p-3 text-sm text-white'
const button = 'rounded-xl bg-purple-500 px-4 py-2 text-sm font-bold text-white disabled:opacity-40'
const localDateTime = (value: string | number) => { const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16) }

export function NightclubCourtesyDialog({ data, accountId, productId, memberId, onClose, onConfirm }: { data: NightclubDataset; accountId?: string; productId?: string; memberId?: string; onClose: () => void; onConfirm: (draft: NightclubCourtesyDraft) => boolean }) {
  const [member, setMember] = useState(memberId || '')
  const [product, setProduct] = useState(productId || '')
  const [account, setAccount] = useState(accountId || '')
  const [search, setSearch] = useState('')
  const [quantity, setQuantity] = useState('1')
  const [beneficiary, setBeneficiary] = useState('')
  const [note, setNote] = useState('')
  const selected = (data.members || []).find(item => item.id === member)
  const balance = selected ? courtesyBalance(data, selected) : null
  const availableMembers = (data.members || []).filter(item => item.name.toLocaleLowerCase().includes(search.toLocaleLowerCase()))
  const openAccounts = data.accounts.filter(item => item.status === 'open')
  const eligible = data.products.filter(item => item.category === 'Botellas' && item.active !== false)
  const submit = () => {
    if (onConfirm({ memberId: member, productId: product, quantity: Number(quantity), accountId: account || undefined, beneficiary, note })) onClose()
  }
  return <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-slate-950/85 p-3"><section role="dialog" aria-modal="true" aria-label="Registrar cortesía de socio" className="my-4 w-full max-w-lg space-y-4 rounded-2xl border border-purple-400/30 bg-slate-900 p-5 shadow-2xl"><div className="flex items-start justify-between"><div><h2 className="text-xl font-black">Registrar cortesía</h2><p className="text-xs text-slate-400">Botella sin cargo, con cupo e inventario trazables.</p></div><button onClick={onClose} aria-label="Cerrar cortesía" className="text-2xl">×</button></div>
    <label className="block text-xs text-slate-300">Buscar socio<input aria-label="Buscar socio" className={`${input} mt-1`} value={search} onChange={event => setSearch(event.target.value)} placeholder="Nombre del socio" /></label>
    <div className="max-h-32 overflow-y-auto rounded-xl border border-slate-700">{availableMembers.map(item => { const left = courtesyBalance(data, item); return <button key={item.id} onClick={() => setMember(item.id)} className={`flex w-full justify-between border-b border-slate-800 px-3 py-2 text-left text-sm ${member === item.id ? 'bg-purple-500/30' : 'hover:bg-slate-800'}`}><span>{item.name}{!item.active && <small className="ml-2 text-amber-300">Inactivo</small>}</span><strong>{left.available} disponibles</strong></button> })}{!availableMembers.length && <p className="p-3 text-sm text-slate-400">Sin socios coincidentes.</p>}</div>
    <div className="grid gap-3 sm:grid-cols-2"><label className="text-xs text-slate-300">Botella<select aria-label="Botella de cortesía" className={`${input} mt-1`} value={product} onChange={event => setProduct(event.target.value)} disabled={!!productId}><option value="">Selecciona botella</option>{eligible.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-xs text-slate-300">Cantidad<input aria-label="Cantidad de botellas" type="number" min="1" step="1" className={`${input} mt-1`} value={quantity} onChange={event => setQuantity(event.target.value)} /></label></div>
    <label className="block text-xs text-slate-300">Mesa / cuenta (opcional)<select aria-label="Mesa de la cortesía" className={`${input} mt-1`} value={account} onChange={event => setAccount(event.target.value)} disabled={!!accountId}><option value="">Sin mesa</option>{openAccounts.map(item => <option key={item.id} value={item.id}>{data.tables.find(table => table.id === item.tableId)?.name || item.tableId}</option>)}</select></label>
    <div className="grid gap-3 sm:grid-cols-2"><label className="text-xs text-slate-300">Beneficiario (opcional)<input aria-label="Beneficiario" className={`${input} mt-1`} value={beneficiary} onChange={event => setBeneficiary(event.target.value)} /></label><label className="text-xs text-slate-300">Observación (opcional)<input aria-label="Observación" className={`${input} mt-1`} value={note} onChange={event => setNote(event.target.value)} /></label></div>
    {selected && balance && <div className="rounded-xl border border-purple-500/30 bg-purple-500/10 p-3 text-sm"><p><strong>{selected.name}</strong> · cupo {balance.quota} · utilizado {balance.used} · disponible {balance.available}</p><p className="mt-1 text-slate-300">Después: {balance.available - Number(quantity || 0)} botella(s) disponible(s).</p><p className="mt-1 text-xs text-slate-400">Período {new Date(balance.start).toLocaleDateString('es-BO')} – {new Date(balance.end).toLocaleDateString('es-BO')}</p></div>}
    <button className={`${button} w-full py-3`} disabled={!selected?.active || !balance?.active || !product || !Number.isInteger(Number(quantity)) || Number(quantity) < 1 || Number(quantity) > (balance?.available || 0) || data.shift?.status !== 'open'} onClick={submit}>Confirmar cortesía · Bs 0,00</button>
  </section></div>
}

export function NightclubMembers({ data, role, onSave, onRegister, onCancel }: { data: NightclubDataset; role: string; onSave: (member: NightclubMember) => boolean; onRegister: (draft: NightclubCourtesyDraft) => boolean; onCancel: (id: string) => boolean }) {
  const [search, setSearch] = useState('')
  const [selectedId, setSelectedId] = useState('')
  const [editing, setEditing] = useState<NightclubMember | null>(null)
  const [courtesyMemberId, setCourtesyMemberId] = useState<string | null>(null)
  const [name, setName] = useState('')
  const [quota, setQuota] = useState('0')
  const [repeatDays, setRepeatDays] = useState('7')
  const [windowDays, setWindowDays] = useState('7')
  const [anchorAt, setAnchorAt] = useState('')
  const [active, setActive] = useState(true)
  const canManage = ['owner', 'admin'].includes(role)
  const canRegister = canManage || ['cashier', 'waiter', 'service'].includes(role)
  const members = useMemo(() => (data.members || []).filter(item => item.name.toLocaleLowerCase().includes(search.toLocaleLowerCase())), [data.members, search])
  const selected = (data.members || []).find(item => item.id === selectedId)
  const records = (data.courtesies || []).filter(item => item.memberId === selectedId).slice().reverse()
  const edit = (member?: NightclubMember) => { const anchor = member?.policy.anchorAt || new Date(Date.now() - 60_000).toISOString(); setEditing(member || { id: crypto.randomUUID(), name: '', active: true, quota: 0, policy: { anchorAt: anchor, windowDays: 7, repeatDays: 7 } }); setName(member?.name || ''); setQuota(String(member?.quota ?? 0)); setRepeatDays(String(member?.policy.repeatDays ?? 7)); setWindowDays(String(member?.policy.windowDays ?? 7)); setAnchorAt(localDateTime(anchor)); setActive(member?.active ?? true) }
  const save = () => { if (!editing || !anchorAt || !Number.isFinite(Date.parse(anchorAt))) return; if (onSave({ ...editing, name: name.trim(), quota: Number(quota), active, policy: { anchorAt: new Date(anchorAt).toISOString(), repeatDays: Number(repeatDays), windowDays: Number(windowDays) } })) setEditing(null) }
  const totalCost = (data.courtesies || []).filter(item => item.status === 'active' && item.cost !== undefined).reduce((sum, item) => sum + (item.cost || 0), 0)
  return <div className="space-y-5"><header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-black">Socios</h1><p className="text-sm text-slate-400">Cupos, cortesías y movimientos de cada período.</p></div><div className="flex gap-2">{canManage && <button className={button} onClick={() => edit()}>+ Nuevo socio</button>}{canRegister && <button className={button} onClick={() => setCourtesyMemberId('')}>+ Registrar cortesía</button>}</div></header>
    <div className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><small className="text-slate-400">Socios activos</small><strong className="mt-1 block text-2xl">{(data.members || []).filter(item => item.active).length}</strong></div><div className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><small className="text-slate-400">Cortesías vigentes</small><strong className="mt-1 block text-2xl">{(data.courtesies || []).filter(item => item.status === 'active').reduce((sum, item) => sum + item.quantity, 0)}</strong></div><div className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><small className="text-slate-400">Costo conocido</small><strong className="mt-1 block text-2xl">{money(totalCost)}</strong></div></div>
    <input aria-label="Buscar socios" placeholder="Buscar socio..." className={input} value={search} onChange={event => setSearch(event.target.value)} />
    <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{members.map(member => { const balance = courtesyBalance(data, member); return <article key={member.id} className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><div className="flex justify-between gap-2"><h2 className="font-bold">{member.name}</h2><span className={`text-xs ${member.active ? 'text-emerald-300' : 'text-amber-300'}`}>{member.active ? 'ACTIVO' : 'INACTIVO'}</span></div><p className="mt-3 text-xs text-slate-400">Cupo {member.policy.windowDays}/{member.policy.repeatDays} días · {balance.active ? 'Período vigente' : 'Fuera de período'}</p><div className="mt-2 flex justify-between text-sm"><span>Asignadas <b>{balance.quota}</b></span><span>Usadas <b>{balance.used}</b></span><span>Disponibles <b className="text-purple-300">{balance.available}</b></span></div><div className="mt-4 flex flex-wrap gap-2"><button onClick={() => setSelectedId(member.id)} className="rounded-lg border border-slate-700 px-3 py-2 text-xs font-bold">Ver movimientos</button>{canRegister && <button onClick={() => setCourtesyMemberId(member.id)} className="rounded-lg bg-purple-500 px-3 py-2 text-xs font-bold">Registrar cortesía</button>}{canManage && <button onClick={() => edit(member)} className="rounded-lg border border-slate-700 px-3 py-2 text-xs font-bold">Editar</button>}</div></article> })}{!members.length && <p className="text-sm text-slate-400">No hay socios. Crea el primero para asignar un cupo.</p>}</div>
    {selected && <section className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><div className="flex justify-between"><div><h2 className="text-xl font-bold">{selected.name}</h2><p className="text-xs text-slate-400">Historial completo; las anulaciones permanecen visibles.</p></div><button onClick={() => setSelectedId('')} aria-label="Cerrar detalle de socio">×</button></div><p className="my-3 text-sm">Cupo {selected.quota} · Utilizadas {courtesyBalance(data, selected).used} · Disponibles {courtesyBalance(data, selected).available}</p><div className="space-y-2">{records.map(record => <div key={record.id} className="flex flex-wrap items-center justify-between gap-2 rounded-xl bg-slate-950 p-3 text-xs"><div><strong>{record.quantity}× {record.productName}</strong><p className="mt-1 text-slate-400">{new Date(record.at).toLocaleString('es-BO')} · {record.beneficiary || 'Sin beneficiario'} · {data.tables.find(table => table.id === record.tableId)?.name || 'Sin mesa'} · {record.actor}</p><p className="text-slate-400">Período {new Date(record.periodStart).toLocaleDateString('es-BO')} · Costo {record.cost === undefined ? 'No configurado' : money(record.cost)} · {record.status === 'cancelled' ? `Anulada por ${record.cancelledBy}` : 'Activa'}</p></div>{record.status === 'active' && canManage && <button onClick={() => onCancel(record.id)} className="rounded-lg border border-amber-500 px-3 py-2 text-amber-300">Anular</button>}</div>)}{!records.length && <p className="text-sm text-slate-400">Sin cortesías registradas.</p>}</div></section>}
    {editing && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/85 p-3"><section role="dialog" aria-modal="true" aria-label="Editar socio" className="w-full max-w-md space-y-3 rounded-2xl border border-slate-700 bg-slate-900 p-5"><div className="flex justify-between"><h2 className="text-xl font-bold">{(data.members || []).some(item => item.id === editing.id) ? 'Editar socio' : 'Nuevo socio'}</h2><button onClick={() => setEditing(null)} aria-label="Cerrar editor">×</button></div><label className="block text-xs">Nombre<input aria-label="Nombre del socio" className={`${input} mt-1`} value={name} onChange={event => setName(event.target.value)} /></label><label className="block text-xs">Cupo de botellas<input aria-label="Cupo de botellas" type="number" min="0" step="1" className={`${input} mt-1`} value={quota} onChange={event => setQuota(event.target.value)} /></label><div className="grid grid-cols-2 gap-2"><label className="text-xs">Repetir cada (días)<input aria-label="Repetir período cada días" type="number" min="1" step="1" className={`${input} mt-1`} value={repeatDays} onChange={event => setRepeatDays(event.target.value)} /></label><label className="text-xs">Ventana activa (días)<input aria-label="Duración de ventana en días" type="number" min="1" step="1" className={`${input} mt-1`} value={windowDays} onChange={event => setWindowDays(event.target.value)} /></label></div><label className="block text-xs">Inicio del primer período<input aria-label="Inicio del período" type="datetime-local" className={`${input} mt-1`} value={anchorAt} onChange={event => setAnchorAt(event.target.value)} /></label><p className="text-xs text-slate-400">Ejemplo: semana 7/7 días; fin de semana 3/7 días, comenzando el viernes. El historial nunca se reinicia.</p><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={active} onChange={event => setActive(event.target.checked)} /> Socio activo</label><button onClick={save} className={`${button} w-full`}>Guardar socio</button></section></div>}
    {courtesyMemberId !== null && <NightclubCourtesyDialog data={data} memberId={courtesyMemberId} onClose={() => setCourtesyMemberId(null)} onConfirm={onRegister} />}
  </div>
}

export function NightclubCourtesyReport({ data }: { data: NightclubDataset }) {
  const records = (data.courtesies || []).slice().reverse()
  const knownCost = records.filter(item => item.status === 'active' && item.cost !== undefined).reduce((sum, item) => sum + (item.cost || 0), 0)
  return <section className="space-y-3 rounded-2xl border border-slate-800 bg-slate-900 p-4"><div><h2 className="text-lg font-bold">Cortesías de socios</h2><p className="text-xs text-slate-400">Unidades entregadas y costo interno conocido; no suman ventas.</p></div><div className="grid gap-2 sm:grid-cols-2"><div className="rounded-xl bg-slate-950 p-3 text-sm">Botellas vigentes <strong className="block text-xl">{records.filter(item => item.status === 'active').reduce((sum, item) => sum + item.quantity, 0)}</strong></div><div className="rounded-xl bg-slate-950 p-3 text-sm">Costo conocido <strong className="block text-xl">{money(knownCost)}</strong></div></div><div className="space-y-2">{records.map(item => <div key={item.id} className="flex flex-wrap justify-between gap-2 border-t border-slate-800 py-2 text-xs"><div><strong>{(data.members || []).find(member => member.id === item.memberId)?.name || item.memberId} · {item.quantity}× {item.productName}</strong><p className="text-slate-400">{new Date(item.at).toLocaleString('es-BO')} · {item.beneficiary || 'Sin beneficiario'} · {item.actor} · período {new Date(item.periodStart).toLocaleDateString('es-BO')}</p></div><span>{item.status === 'cancelled' ? 'ANULADA' : item.cost === undefined ? 'Costo no configurado' : money(item.cost)}</span></div>)}{!records.length && <p className="text-sm text-slate-400">Todavía no hay cortesías de socios.</p>}</div></section>
}
