import { useState } from 'react'
import type { NightclubCustomer, NightclubDataset } from '../domain/nightclubAccounts'
import { normalizeCustomerPhone } from '../../restaurant/domain/restaurantCustomers'

export function NightclubCustomers({ data, companyName, onSave }: { data: NightclubDataset; companyName: string; onSave: (customer: NightclubCustomer) => void }) {
  const [query, setQuery] = useState('')
  const [editing, setEditing] = useState<NightclubCustomer | null>(null)
  const [creating, setCreating] = useState(false)
  const [name, setName] = useState('')
  const [phone, setPhone] = useState('')
  const [notes, setNotes] = useState('')
  const openForm = (customer?: NightclubCustomer) => { setEditing(customer || null); setCreating(true); setName(customer?.name || ''); setPhone(customer?.phone || ''); setNotes(customer?.notes || '') }
  const save = () => { if (!name.trim()) return; onSave({ id: editing?.id || crypto.randomUUID(), name: name.trim(), phone: phone.trim(), notes: notes.trim(), active: true, visits: editing?.visits || 0, totalSpent: editing?.totalSpent || 0 }); setCreating(false) }
  const rows = data.customers.filter(customer => `${customer.name} ${customer.phone}`.toLowerCase().includes(query.toLowerCase()))
  const metrics = (customer: NightclubCustomer) => { const paid = data.accounts.filter(account => account.customerId === customer.id && account.status === 'closed'); return { visits: customer.visits + paid.length, spent: customer.totalSpent + paid.reduce((sum, item) => sum + item.subtotal, 0) } }
  return <div className="space-y-5"><header className="flex justify-between gap-3"><div><h1 className="text-2xl font-black">Clientes</h1><p className="text-sm text-slate-400">Contactos, consumo y reservas del club.</p></div><button onClick={() => openForm()} className="rounded-xl bg-purple-500 px-4 py-2 text-sm font-bold">Nuevo cliente</button></header><input aria-label="Buscar cliente" placeholder="Buscar por nombre o teléfono" value={query} onChange={event => setQuery(event.target.value)} className="w-full rounded-xl border border-slate-700 bg-slate-900 p-3" /><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{rows.map(customer => { const stats = metrics(customer); const number = normalizeCustomerPhone('591', customer.phone); return <article key={customer.id} className="rounded-2xl border border-slate-800 bg-slate-900 p-4"><strong>{customer.name}</strong><p className="mt-1 text-sm text-slate-400">{customer.phone || 'Sin teléfono'}</p><p className="mt-3 text-sm">{stats.visits} visitas · Bs {stats.spent.toFixed(2)} consumidos</p>{customer.notes && <p className="mt-2 text-xs text-slate-400">{customer.notes}</p>}<div className="mt-3 flex gap-2"><button onClick={() => openForm(customer)} className="rounded-lg border border-slate-700 px-3 py-2 text-xs font-bold">Editar</button>{number && <a href={`https://wa.me/${number}?text=${encodeURIComponent(`Hola ${customer.name}, te escribimos de ${companyName}.`)}`} target="_blank" rel="noopener noreferrer" className="rounded-lg border border-emerald-700 px-3 py-2 text-xs font-bold text-emerald-300">WhatsApp</a>}</div></article> })}{!rows.length && <p className="text-sm text-slate-400">Aún no hay clientes.</p>}</div>
    {creating && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/80 p-4"><section role="dialog" aria-modal="true" aria-label="Cliente" className="w-full max-w-md space-y-3 rounded-2xl border border-slate-700 bg-slate-900 p-5"><h2 className="text-lg font-bold">{editing ? 'Editar cliente' : 'Nuevo cliente'}</h2><input aria-label="Nombre del cliente" placeholder="Nombre" value={name} onChange={event => setName(event.target.value)} className="w-full rounded-xl bg-slate-950 p-3" /><input aria-label="Teléfono del cliente" placeholder="Teléfono" value={phone} onChange={event => setPhone(event.target.value)} className="w-full rounded-xl bg-slate-950 p-3" /><textarea aria-label="Notas del cliente" placeholder="Notas opcionales" value={notes} onChange={event => setNotes(event.target.value)} className="w-full rounded-xl bg-slate-950 p-3" /><div className="flex gap-2"><button onClick={() => setCreating(false)} className="flex-1 rounded-xl border border-slate-700 p-3">Cancelar</button><button onClick={save} disabled={!name.trim()} className="flex-1 rounded-xl bg-purple-500 p-3 font-bold disabled:opacity-40">Guardar</button></div></section></div>}
  </div>
}
