import { Pencil, Plus, Trash2 } from 'lucide-react'
import { useState } from 'react'
import type { NightclubDataset, NightclubTable } from '../domain/nightclubAccounts'
import type { TableDraft, ZoneDraft } from '../domain/nightclubFloor'

const money = (value: number) => `Bs ${value.toLocaleString('es-BO', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`

export function NightclubFloor({ data, onSelectTable, onSaveZone, onSaveTable, onDeleteZone, onDeleteTable, embedded = false }: {
  data: NightclubDataset
  onSelectTable: (id: string) => void
  onSaveZone: (draft: ZoneDraft) => boolean
  onSaveTable: (draft: TableDraft) => boolean
  onDeleteZone?: (id: string) => boolean
  onDeleteTable?: (id: string) => boolean
  embedded?: boolean
}) {
  const [zoneDraft, setZoneDraft] = useState<ZoneDraft | null>(null)
  const [tableDraft, setTableDraft] = useState<TableDraft | null>(null)
  const [deleting, setDeleting] = useState<{ kind: 'zone' | 'table'; id: string; name: string; blocked?: string } | null>(null)
  const [managing, setManaging] = useState(embedded)
  const newTable = (zoneId: string): TableDraft => ({ id: '', name: '', zoneId, capacity: 4, status: 'available' })
  const saveZone = () => { if (zoneDraft && onSaveZone(zoneDraft)) setZoneDraft(null) }
  const saveTable = () => { if (tableDraft && onSaveTable(tableDraft)) setTableDraft(null) }
  return <div className="space-y-5">
    {!embedded && <header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-semibold">Salón, VIP y reservados</h1><p className="text-sm text-slate-400">Selecciona una mesa para ver su cuenta y añadir rondas.</p></div><button onClick={() => setManaging(value => !value)} className="rounded-xl border border-amber-300/40 px-4 py-2 text-sm font-bold text-amber-200">{managing ? 'Terminar edición' : 'Administrar salón'}</button></header>}
    {managing && <button onClick={() => setZoneDraft({ id: '', name: '' })} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-amber-300 px-4 text-sm font-bold text-[#07111a]"><Plus size={16} />Nueva zona</button>}
    {data.zones.slice().sort((a, b) => a.sortOrder - b.sortOrder).map(zone => {
      const tables = data.tables.filter(table => table.zoneId === zone.id)
      return <section key={zone.id} className="rounded-xl border border-white/10 bg-[#07111a]/60 p-3"><div className="mb-3 flex flex-wrap items-center gap-2"><h2 className="mr-auto text-sm font-bold uppercase tracking-wider text-amber-200">{zone.name}</h2>{managing && <><button aria-label={`Editar ${zone.name}`} onClick={() => setZoneDraft({ id: zone.id, name: zone.name })} className="grid h-9 w-9 place-items-center rounded-lg border border-white/10 text-slate-300"><Pencil size={14} /></button>{onDeleteZone && <button aria-label={`Eliminar ${zone.name}`} onClick={() => setDeleting({ kind: 'zone', id: zone.id, name: zone.name, blocked: tables.length ? 'No se puede eliminar esta zona porque contiene mesas.' : undefined })} className="grid h-9 w-9 place-items-center rounded-lg border border-rose-400/20 text-rose-300"><Trash2 size={14} /></button>}<button onClick={() => setTableDraft(newTable(zone.id))} className="inline-flex h-9 items-center gap-1 rounded-lg bg-amber-300 px-3 text-xs font-bold text-[#07111a]"><Plus size={13} />Mesa</button></>}</div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{tables.map(table => {
        const account = data.accounts.find(item => item.id === table.activeAccountId && item.status !== 'closed')
        return <article key={table.id} className={`rounded-xl border p-3 ${table.status === 'available' ? 'border-emerald-400/25 bg-emerald-400/5' : table.status === 'reserved' ? 'border-amber-300/30 bg-amber-300/5' : table.status === 'bill_requested' ? 'border-cyan-400/25 bg-cyan-400/5' : 'border-rose-400/25 bg-rose-400/5'}`}><button onClick={() => onSelectTable(table.id)} className="w-full text-left"><span className="text-[10px] font-bold uppercase text-slate-400">{table.status === 'available' ? 'Libre' : table.status === 'reserved' ? 'Reservada' : table.status === 'bill_requested' ? 'Por cobrarse' : 'Ocupada'}</span><strong className="mt-1 block text-base">{table.name}</strong><span className="text-xs text-slate-400">{table.capacity} personas</span>{account && <strong className="mt-2 block text-amber-200">{money(account.subtotal)} · {account.rounds.length} rondas</strong>}{table.reservationName && <span className="mt-2 block text-xs text-amber-100">{table.reservationName}</span>}</button>{managing && <div className="mt-3 flex gap-2"><button onClick={() => setTableDraft({ id: table.id, name: table.name, zoneId: table.zoneId, capacity: table.capacity, status: table.status })} className="inline-flex h-9 flex-1 items-center justify-center gap-1 rounded-lg border border-white/10 text-xs"><Pencil size={13} />Editar</button>{onDeleteTable && <button aria-label={`Eliminar ${table.name}`} onClick={() => setDeleting({ kind: 'table', id: table.id, name: table.name, blocked: table.activeAccountId ? 'Finaliza la cuenta activa antes de eliminar la mesa.' : data.reservations.some(item => item.tableId === table.id && item.status === 'confirmed') ? 'Cancela la reserva antes de eliminar la mesa.' : undefined })} className="grid h-9 w-9 place-items-center rounded-lg border border-rose-400/20 text-rose-300"><Trash2 size={14} /></button>}</div>}</article>
      })}{!tables.length && <p className="text-sm text-slate-500">Todavía no hay mesas en esta zona.</p>}</div></section>
    })}
    {zoneDraft && <Modal label="Zona"><h2 className="text-lg font-bold">{zoneDraft.id ? 'Editar zona' : 'Nueva zona'}</h2><input autoFocus aria-label="Nombre de la zona" placeholder="Nombre de la zona" value={zoneDraft.name} onChange={event => setZoneDraft({ ...zoneDraft, name: event.target.value })} className="w-full rounded-xl bg-slate-950 p-3" /><Actions onCancel={() => setZoneDraft(null)} onSave={saveZone} disabled={!zoneDraft.name.trim()} /></Modal>}
    {tableDraft && <Modal label="Mesa"><h2 className="text-lg font-bold">{tableDraft.id ? 'Editar mesa' : 'Nueva mesa'}</h2><input autoFocus aria-label="Nombre de la mesa" placeholder="Mesa 12 o VIP 3" value={tableDraft.name} onChange={event => setTableDraft({ ...tableDraft, name: event.target.value })} className="w-full rounded-xl bg-slate-950 p-3" /><label className="block text-xs text-slate-400">Zona<select aria-label="Zona de la mesa" value={tableDraft.zoneId} onChange={event => setTableDraft({ ...tableDraft, zoneId: event.target.value })} className="mt-1 w-full rounded-xl bg-slate-950 p-3 text-sm text-white">{data.zones.map(zone => <option key={zone.id} value={zone.id}>{zone.name}</option>)}</select></label><label className="block text-xs text-slate-400">Capacidad<input aria-label="Capacidad de la mesa" type="number" min="1" max="100" value={tableDraft.capacity} onChange={event => setTableDraft({ ...tableDraft, capacity: Number(event.target.value) })} className="mt-1 w-full rounded-xl bg-slate-950 p-3 text-sm text-white" /></label>{tableDraft.id && <label className="block text-xs text-slate-400">Estado<select aria-label="Estado de la mesa" value={tableDraft.status} disabled={!!data.tables.find(table => table.id === tableDraft.id)?.activeAccountId} onChange={event => setTableDraft({ ...tableDraft, status: event.target.value as NightclubTable['status'] })} className="mt-1 w-full rounded-xl bg-slate-950 p-3 text-sm text-white disabled:opacity-50"><option value="available">Libre</option>{data.tables.find(table => table.id === tableDraft.id)?.status === 'reserved' && <option value="reserved">Reservada</option>}{!!data.tables.find(table => table.id === tableDraft.id)?.activeAccountId && <><option value="occupied">Ocupada</option><option value="bill_requested">Por cobrarse</option></>}</select></label>}<Actions onCancel={() => setTableDraft(null)} onSave={saveTable} disabled={!tableDraft.name.trim() || !tableDraft.zoneId || tableDraft.capacity < 1} /></Modal>}
    {deleting && <Modal label={`Eliminar ${deleting.kind === 'zone' ? 'zona' : 'mesa'}`}><h2 className="text-lg font-bold">Eliminar {deleting.kind === 'zone' ? 'zona' : 'mesa'}</h2><p className="text-sm text-slate-300">{deleting.blocked || `¿Eliminar “${deleting.name}”?`}</p><div className="flex gap-2"><button onClick={() => setDeleting(null)} className="flex-1 rounded-xl border border-slate-700 p-3">{deleting.blocked ? 'Entendido' : 'Cancelar'}</button>{!deleting.blocked && <button onClick={() => { const ok = deleting.kind === 'zone' ? onDeleteZone?.(deleting.id) : onDeleteTable?.(deleting.id); if (ok) setDeleting(null) }} className="flex-1 rounded-xl bg-rose-500 p-3 font-bold text-white">Eliminar {deleting.kind === 'zone' ? 'zona' : 'mesa'}</button>}</div></Modal>}
  </div>
}

function Modal({ label, children }: { label: string; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/80 p-4"><section role="dialog" aria-modal="true" aria-label={label} className="w-full max-w-sm space-y-3 rounded-2xl border border-slate-700 bg-[#0d1720] p-5">{children}</section></div> }
function Actions({ onCancel, onSave, disabled }: { onCancel: () => void; onSave: () => void; disabled: boolean }) { return <div className="flex gap-2"><button onClick={onCancel} className="flex-1 rounded-xl border border-slate-700 p-3">Cancelar</button><button onClick={onSave} disabled={disabled} className="flex-1 rounded-xl bg-amber-300 p-3 font-bold text-[#07111a] disabled:opacity-40">Guardar</button></div> }
