import type { NightclubDataset, NightclubRoundStatus } from '../domain/nightclubAccounts'
import { nightclubAccountLabel } from '../domain/nightclubAccounts'

const labels: Record<NightclubRoundStatus, string> = { pending: 'Pendiente', preparing: 'En preparación', ready: 'Listo', delivered: 'Entregado al mesero', cancelled: 'Anulado' }

export function NightclubBar({ data, onAdvance }: { data: NightclubDataset; onAdvance: (accountId: string, roundId: string) => void }) {
  const rounds = data.accounts.filter(account => account.status !== 'closed').flatMap(account => account.rounds.filter(round => round.status !== 'delivered' && round.status !== 'cancelled' && round.items.some(item => item.preparationArea !== 'Directo')).map(round => ({ account, round })))
  return <div className="space-y-4"><header><h1 className="text-2xl font-black">Barra</h1><p className="text-sm text-slate-400">Preparación y entrega al mesero. Los productos de entrega directa no ingresan aquí.</p></header><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{rounds.map(({account,round}) => <article key={round.id} className="rounded-xl border border-slate-700 bg-[#121b20] p-4"><div className="flex items-start justify-between"><div><strong>{nightclubAccountLabel(account, data)}</strong><span className="block text-xs text-slate-400">Ronda #{round.sequence} · {account.openedBy}</span></div><span className="rounded-full bg-slate-800 px-2 py-1 text-[11px] font-bold text-amber-200">{labels[round.status]}</span></div><div className="my-4 space-y-2">{round.items.filter(item => item.preparationArea !== 'Directo').map(item => <p key={item.id} className="flex justify-between border-b border-slate-800 pb-2 text-sm"><span>{item.quantity}× {item.name}</span><span className="text-slate-500">Barra</span></p>)}</div><button onClick={() => onAdvance(account.id, round.id)} className="h-11 w-full rounded-xl bg-amber-400 font-bold text-slate-950">{round.status === 'pending' ? 'Iniciar preparación' : round.status === 'preparing' ? 'Marcar listo' : 'Entregar al mesero'}</button></article>)}{!rounds.length && <p className="rounded-xl border border-dashed border-slate-700 p-6 text-sm text-slate-400">No hay preparaciones pendientes.</p>}</div></div>
}
